@startuml
skinparam activityFontSize 4
skinparam activityDiamondFontSize 6
skinparam activityArrowFontSize 24
skinparam activityFontColor red

:start;
if (some) then (yes)
repeat
  :first action;
  :second action;
repeatwhile (data to treat)
else (no)
  :me;
endif
:end of process;
@enduml
