/**
 * Freshness guard for every committed oracle cache (object-close D4, widened
 * to all cached types by SI16).
 *
 * The bug this exists to prevent already happened and nothing failed:
 * `test-results/dot-cache/object/*​/in.svg` was captured before the 0.2.0
 * SVG-reduction port (`DIVERGENCES.md` → "SVG emission tracks upstream's
 * reduced form"), so `svg-conformance-census.ts object` compared this port's
 * current output against a pre-reduction oracle and reported 0/80 — an
 * artifact that sat there, green, while the real number was 23/80. A gate that
 * cannot detect its own stale input is not a gate.
 *
 * **Then it recurred, exactly as predicted, because the guard was scoped to
 * one type.** SI16 measured `class`, `state` and `usecase` as stale by the
 * same mechanism: their caches were last written by `9b54513f`, which
 * `git merge-base --is-ancestor` places 54 minutes BEFORE the SVG-reduction
 * merge `7c30f8ae`. Their censuses were reporting 2/722, 0/271 and 2/93 —
 * artifacts, not measurements. So the sentinel list below covers every type
 * with a committed cache, not just the one that was caught first.
 *
 * Staleness *was* believed to be a whole-cache property — one capture run
 * writes every file for a type — so ONE sentinel PER TYPE was thought enough.
 *
 * **That assumption is false, and it failed exactly as this file warns.** On
 * 2026-09-02, 244 of 266 `component` oracles were found still in the
 * pre-SVG-reduction form while 22 were not: the cache had been PARTIALLY
 * recaptured. The `component` sentinel (`babafi-51-dixi026`) is one of the 22
 * fresh files, so this suite was green while 91% of that cache was stale and
 * every description conformance number measured against it was an artifact.
 * Regenerating it moved description's weighted total by -7.8%.
 *
 * So there are now TWO checks. The per-type sentinel above proves the cache is
 * not WHOLLY stale; {@link EMISSION_FORM_PROBES} below proves it is not
 * PARTIALLY stale, across every cached file, without rendering 2 500 fixtures.
 * A gate that cannot detect its own stale input is not a gate — and one that
 * samples a single file cannot detect a heterogeneous one.
 *
 * **Compares BYTES, deliberately.** Every other suite here goes through
 * `compare.ts`, whose DOM parse is blind by construction to entity form and
 * colour form (`normalize.ts`); the pre-0.2.0 staleness lived largely in
 * exactly those channels — `font-family`/`lengthAdjust` attributes, `#000000`
 * vs `#000`, 4-decimal coordinates. A guard that inherited that blindness
 * would have missed the very bug it is here to catch.
 *
 * The jar is byte-deterministic for a given input under
 * `PLANTUML_DETERMINISTIC_TEXT` (verified: two consecutive renders of a
 * sentinel are `cmp`-identical, and identical to the committed cache), and its
 * output does not depend on the input FILENAME (verified by rendering one
 * sentinel as `in.puml` and as `object.puml` — byte-identical), which is what
 * lets all sentinels share a single JVM start below.
 *
 * Costs ONE JVM start (~1–2s) for the whole set rather than one per type.
 * Runs in `npm test` rather than as a census preflight so that CI executes it
 * on every change, not only when someone chooses to run the census.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const JAR = join(REPO, 'oracle/dist/plantuml-oracle.jar');
const RENDER = join(REPO, 'scripts/oracle-render.sh');
const CACHE = join(REPO, 'test-results/dot-cache');

interface Sentinel {
  /** Cache directory under `test-results/dot-cache/`. */
  readonly type: string;
  /** Fixture directory inside it. */
  readonly slug: string;
}

/**
 * One fixture per cached type. Each was byte-verified against a fresh render
 * at the time it was added, so a failure here means the CACHE moved (or the
 * jar did), never that the sentinel was a bad pick.
 *
 * `object`'s is the fixture hand-verified during object-close planning;
 * `sequence`'s (`bacupi-77-fuke586`, its cache dir's `localeCompare`-first
 * slug, per D7 of `sequence-oracle-harness`) was `cmp`-verified against
 * `oracle-render.sh` output during T5 of that mission; the rest are each
 * type's first fixture, checked by `cmp` during SI16.
 *
 * **`dot` is deliberately absent.** `@startdot` is a passthrough: the jar
 * shells out to the HOST graphviz binary, so its cached SVG embeds
 * `<!-- Generated by graphviz version … -->`. Measured during SI16, the cached
 * and fresh renders of `dot/bemepi-16-kuzo249` are the same length and differ
 * on that line alone (`15.1.0 (20260618.0150)` vs `15.1.1 (20260805.0921)`).
 * A byte guard there would report the local graphviz version, not cache
 * freshness — and that cache gates nothing: the dot ratchet reads
 * `oracle/goldens/svg-dot/`, and the census only touches it when `dot` is
 * asked for by name.
 */
const SENTINELS: readonly Sentinel[] = [
  { type: 'component', slug: 'babafi-51-dixi026' },
  { type: 'usecase', slug: 'baxodi-80-doto381' },
  { type: 'class', slug: 'bajotu-30-soku184' },
  { type: 'object', slug: 'beruju-17-jigi548' },
  { type: 'state', slug: 'bajelo-54-dixe684' },
  { type: 'sequence', slug: 'bacupi-77-fuke586' },
  { type: 'json', slug: 'babico-87-soxo095' },
  { type: 'yaml', slug: 'YAML-attribute-hierarchy' },
  { type: 'hcl', slug: 'citoda-80-dimi195' },
  // `movexa-27-rexe388` (activity-oracle-harness T3): swimlanes plus an
  // if/then/else branch, `test-results/dot-cache/activity`'s median oracle by
  // file size (4255 of 291 non-error bytes) and `.puml` line count (11 of
  // 291) — representative of the corpus's typical shape, not a two-line
  // degenerate case (`activity-creole-table`, a 2-statement outlier, was
  // rejected for that reason). `cmp`-verified against `oracle-render.sh`
  // output during T3.
  { type: 'activity', slug: 'movexa-27-rexe388' },
];

const cachedSvg = (s: Sentinel): string => join(CACHE, s.type, s.slug, 'in.svg');
const cachedPuml = (s: Sentinel): string => join(CACHE, s.type, s.slug, 'in.puml');

/**
 * Render every sentinel in a single jar invocation. Each is copied in under
 * `<type>.puml` so the outputs land side by side instead of overwriting one
 * shared `in.svg`.
 */
function renderAll(out: string): void {
  for (const s of SENTINELS) copyFileSync(cachedPuml(s), join(out, `${s.type}.puml`));
  const pumls = SENTINELS.map((s) => join(out, `${s.type}.puml`));
  execFileSync(RENDER, [out, ...pumls], { stdio: 'pipe' });
}

function staleMessage(s: Sentinel, fresh: Buffer, cached: Buffer): string {
  return (
    `test-results/dot-cache/${s.type}/${s.slug}/in.svg does NOT match a fresh render of `
    + `oracle/dist/plantuml-oracle.jar (fresh ${fresh.length} bytes, cached ${cached.length}). `
    + `The committed ${s.type} oracle cache is STALE: every census and survey number measured `
    + 'against it is an artifact, not a measurement. Re-capture it — see '
    + 'plans/object-close/batch-0/T1-recapture-oracle.md for the procedure — rather than '
    + 'relaxing this check.'
  );
}

describe('oracle cache freshness (object-close D4, all types per SI16)', () => {
  const haveJar = existsSync(JAR);
  let out = '';

  beforeAll(() => {
    if (!haveJar) return;
    out = mkdtempSync(join(tmpdir(), 'oracle-freshness-'));
    renderAll(out);
  });

  afterAll(() => {
    if (out) rmSync(out, { recursive: true, force: true });
  });

  it.each(SENTINELS.map((s) => [s.type, s] as const))(
    "%s's cached in.svg is byte-identical to a fresh render of the pinned jar",
    (_type, s) => {
      if (!haveJar) {
        // Same graceful degradation every oracle suite here uses: a
        // contributor without the jar is not a failing build.
        console.warn(`skipped: no oracle jar at ${JAR} — cannot check ${s.type} cache freshness`);
        expect(existsSync(cachedSvg(s))).toBe(true);
        return;
      }
      const fresh = readFileSync(join(out, `${s.type}.svg`));
      const cached = readFileSync(cachedSvg(s));
      expect(fresh.equals(cached), staleMessage(s, fresh, cached)).toBe(true);
    },
  );

  /**
   * A marker of a SUPERSEDED emission form: a coordinate written to four or
   * more decimals. The jar rounds to three, so a cached file carrying
   * `x="260.0688"` was written by an older one.
   *
   * **Exactly one probe, deliberately.** Three others were tried and are
   * unsound, each for its own reason, and they are recorded here so nobody
   * re-adds them:
   *
   *  - *per-`<text>` `font-family`* — legitimate today. The common family is
   *    hoisted to the parent `<g>`, but a run that DIFFERS still carries its
   *    own; a `""monospace""` creole run is the everyday case. Flagged 79
   *    sequence and 23 class oracles that are perfectly fresh.
   *  - *per-`<text>` `lengthAdjust`* — same shape, same failure.
   *  - *six-digit hex fill* — the jar shortens `#RRGGBB` to `#RGB` only when
   *    each pair repeats. `#F1F1F1` cannot compress and stays six digits.
   *    Flagged 87 usecase oracles that are fresh.
   *
   * The rule the survivor satisfies and the others do not: it must be
   * something the current jar can NEVER emit, not merely something it emits
   * less often. Presence is the only signal — absence proves nothing, since a
   * fixture may have no fractional coordinate at all.
   */
  const SUPERSEDED_FORM = {
    name: 'coordinate at four or more decimals (the jar rounds to three)',
    re: /"-?\d+\.\d{4,}"/,
  } as const;

  it.each(SENTINELS.map((s) => [s.type, s] as const))(
    'every %s oracle shares the emission form of a fresh render, not just the sentinel',
    (type, s) => {
      if (!haveJar) {
        console.warn(`skipped: no oracle jar at ${JAR} — cannot check ${type} cache homogeneity`);
        expect(existsSync(cachedSvg(s))).toBe(true);
        return;
      }
      // Only a form the CURRENT jar never produces can convict a cached file.
      const fresh = readFileSync(join(out, `${type}.svg`), 'utf8');
      if (SUPERSEDED_FORM.re.test(fresh)) return;

      const dir = join(CACHE, type);
      const offenders = readdirSync(dir).filter((slug) => {
        const svg = join(dir, slug, 'in.svg');
        return existsSync(svg) && SUPERSEDED_FORM.re.test(readFileSync(svg, 'utf8'));
      });
      expect(
        offenders.length,
        `${String(offenders.length)} of the ${type} oracles carry a ${SUPERSEDED_FORM.name}, `
          + `which the pinned jar no longer emits — so that cache was captured by MORE THAN ONE `
          + `jar and is PARTIALLY stale. The per-type sentinel cannot see this: on 2026-09-02 `
          + `244 of 266 component oracles were stale while its sentinel was fresh. Re-capture `
          + `the whole type. First few: ${offenders.slice(0, 5).join(', ')}`,
      ).toBe(0);
    },
  );
});
