/**
 * Renders `packages/stdlib-all/generated/index.{js,d.ts}` -- a re-export of
 * every non-GPL `@knowvah/plantuml-stdlib*` package (`decisions.md` D2: `adaml`
 * is GPL and is never included here).
 *
 * SI12 ADR-4: after SI12, `stdlib-aws` and `stdlib-tupadr3` no longer ship
 * eager bundles -- only remote manifests. A bare `export * from` would
 * silently hand back less than this package's README promises, so the
 * re-export list is explicit and enumerated by name (auditable, and pinnable
 * by `tests/unit/stdlib-all-exports.test.ts`) rather than `export *`:
 * `stdlib`'s five eager bundles (six export bindings -- `bootstrap` carries
 * both the alias and its `bootstrap1_13_1` target) plus the three remote
 * manifests `awslib14Remote`, `awslibRemote`, `tupadr3Remote`.
 */

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/build-stdlib-packages.ts -- DO NOT EDIT.\n' +
  '// Regenerate with: npm run build:stdlib\n';

function reExportAllLines(): string {
  return (
    'export { c4, archimate, cloudinsight, cloudogu, bootstrap, bootstrap1_13_1 } ' +
    "from '@knowvah/plantuml-stdlib';\n" +
    "export { awslib14Remote, awslibRemote } from '@knowvah/plantuml-stdlib-aws';\n" +
    "export { tupadr3Remote } from '@knowvah/plantuml-stdlib-tupadr3';\n"
  );
}

export function emitAllIndexJs(): string {
  return GENERATED_HEADER + '\n' + reExportAllLines();
}

export function emitAllIndexDts(): string {
  return GENERATED_HEADER + '\n' + reExportAllLines();
}
