/** Renders a package's `generated/index.{js,d.ts}` -- re-exports every
 * named binding from every one of its `GeneratedModule`s.
 *
 * SI12 ADR-1/ADR-2: a spec with no eager `modules` (its eager encoding is
 * never emitted -- `stdlib-aws`, `stdlib-tupadr3`) re-exports its REMOTE
 * manifest bindings instead, so `.` keeps handing back something a
 * consumer of that package can actually use.
 */

import type { GeneratedModule, PackageSpec } from './types.js';

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/build-stdlib-packages.ts -- DO NOT EDIT.\n' +
  '// Regenerate with: npm run build:stdlib\n';

function reExportLine(mod: GeneratedModule): string {
  const names = mod.exports.map((exp) => exp.exportName).join(', ');
  return `export { ${names} } from './${mod.fileBaseName}.js';\n`;
}

/** An eager export's JS identifier, e.g. `tupadr3`, gets its remote
 * sibling's identifier by suffixing `Remote` -- mirrors
 * `emit-remote-manifest.ts#remoteExportName` exactly (duplicated here rather
 * than imported: that helper is private and this task's write-set excludes
 * that file -- the same precedent `emit-remote-manifest.ts` itself sets by
 * duplicating `read-bundle.ts#isPumlFile`). */
function remoteReExportLine(mod: GeneratedModule): string {
  const names = mod.exports.map((exp) => `${exp.exportName}Remote`).join(', ');
  return `export { ${names} } from './${mod.fileBaseName}.remote.js';\n`;
}

/** SI12 ADR-1: `spec.modules` present -> re-export the eager bindings.
 * Absent -> re-export the remote manifest bindings instead (ADR-2: absent
 * `modules` means no eager module was emitted for this package at all). */
function indexLines(spec: PackageSpec): string {
  if (spec.modules !== undefined) {
    return spec.modules.map(reExportLine).join('');
  }
  return (spec.remoteModules ?? []).map(remoteReExportLine).join('');
}

export function emitIndexJs(spec: PackageSpec): string {
  return GENERATED_HEADER + '\n' + indexLines(spec);
}

export function emitIndexDts(spec: PackageSpec): string {
  return GENERATED_HEADER + '\n' + indexLines(spec);
}
