/**
 * Renders one `GeneratedModule` (types.ts) into a remote-manifest `.js` +
 * `.d.ts` pair -- the SI11a sibling of `emit-module.ts`'s eager emitter.
 * Same bundle, same key ordering, but `{ name, aliasOf?, files: { key ->
 * REAL relative path } }` -- no content
 * (`plans/si11a-per-resource-stdlib-fetch/decisions.md` ADR-1).
 *
 * ADR-3: the value is the bundle-relative PATH, case preserved, not derived
 * from the key by convention -- 890 of 891 `awslib14` paths contain
 * uppercase (`Storage/SimpleStorageService.puml`) while `derivePumlKey`
 * lowercases every key, so path-by-convention would require renaming
 * vendored files (a mission stop condition). Keys reuse
 * `read-bundle.ts#derivePumlKey` verbatim -- only the walk+filter (which
 * files count as `.puml` resources) is duplicated locally, because
 * `read-bundle.ts#isPumlFile` is private and this task's write-set excludes
 * that file.
 *
 * Every key and every path value goes through `JSON.stringify`, matching
 * `emit-module.ts`'s VERBATIM discipline: escaping, not transformation.
 */

import { join } from 'node:path';

import { walkFiles } from '../vendor-stdlib/walk.js';
import { derivePumlKey } from './read-bundle.js';
import type { AliasBundleExport, ConcreteBundleExport, GeneratedModule } from './types.js';

const PUML_SUFFIX = '.puml';

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/build-stdlib-packages.ts -- DO NOT EDIT.\n' +
  '// Regenerate with: npm run build:stdlib\n';

const DTS_IMPORT = `import type { StdlibRemoteManifest } from 'plantuml-ts';\n`;

function isPumlFile(relPath: string): boolean {
  return relPath.toLowerCase().endsWith(PUML_SUFFIX);
}

/** An eager export's JS identifier, e.g. `tupadr3`, gets its remote
 * sibling's identifier by suffixing `Remote` -- matches the manifest shape
 * sample in T5's brief (`tupadr3` -> `tupadr3Remote`). */
function remoteExportName(exportName: string): string {
  return `${exportName}Remote`;
}

/** Reads every `.puml` file under `assetsStdlibDir/assetFolder` into a
 * key -> REAL relative path map (case preserved), keyed per
 * `derivePumlKey`. Same walk and `.puml` filter as
 * `read-bundle.ts#readBundleFiles`, but keeps the path instead of reading
 * the file's content -- the manifest ships paths, not content (ADR-1). */
function readBundlePaths(assetsStdlibDir: string, assetFolder: string): Record<string, string> {
  const bundleRoot = join(assetsStdlibDir, assetFolder);
  const paths: Record<string, string> = {};

  for (const { relPath } of walkFiles(bundleRoot)) {
    if (!isPumlFile(relPath)) {
      continue;
    }
    paths[derivePumlKey(relPath)] = relPath;
  }

  return paths;
}

function emitConcreteRemoteJs(bundle: ConcreteBundleExport, assetsStdlibDir: string): string {
  const paths = readBundlePaths(assetsStdlibDir, bundle.assetFolder);
  const fileLines = Object.keys(paths)
    .sort()
    .map((key) => `    ${JSON.stringify(key)}: ${JSON.stringify(paths[key])},`)
    .join('\n');

  return (
    `export const ${remoteExportName(bundle.exportName)} = {\n` +
    `  name: ${JSON.stringify(bundle.bundleName)},\n` +
    `  files: {\n${fileLines}\n  },\n` +
    `};\n`
  );
}

function emitAliasRemoteJs(alias: AliasBundleExport): string {
  return (
    `export const ${remoteExportName(alias.exportName)} = {\n` +
    `  name: ${JSON.stringify(alias.bundleName)},\n` +
    `  aliasOf: ${JSON.stringify(alias.aliasOf)},\n` +
    `  files: {},\n` +
    `};\n`
  );
}

/** Renders one `GeneratedModule`'s remote-manifest `.js` body. */
export function emitRemoteManifestJs(mod: GeneratedModule, assetsStdlibDir: string): string {
  const bodies = mod.exports.map((exp) =>
    exp.kind === 'concrete' ? emitConcreteRemoteJs(exp, assetsStdlibDir) : emitAliasRemoteJs(exp),
  );
  return GENERATED_HEADER + '\n' + bodies.join('\n');
}

/** Renders one `GeneratedModule`'s remote-manifest `.d.ts` body -- a
 * type-only import of `StdlibRemoteManifest` plus one `declare const` per
 * export. */
export function emitRemoteManifestDts(mod: GeneratedModule): string {
  const decls = mod.exports
    .map((exp) => `export declare const ${remoteExportName(exp.exportName)}: StdlibRemoteManifest;\n`)
    .join('');
  return GENERATED_HEADER + '\n' + DTS_IMPORT + '\n' + decls;
}
