/**
 * unwind-U4: `scaleBilinear` against JDK 21 `AffineTransformOp`
 * `TYPE_BILINEAR` reference rasters (`tests/fixtures/unwind-U4/bilinear/`,
 * generated by its `Bl.java`, which mirrors `PortableImageAwt.java:113-127`).
 */
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { scaleBilinear, scaledRasterSize } from '../../../../../src/core/klimt/sprite/sprite-bilinear.js';
import type { RgbaBitmap } from '../../../../../src/core/klimt/sprite/sprite-raster.js';

const CASES = 'tests/fixtures/unwind-U4/bilinear/cases.txt';
/** Interior channel values the clean-room model misses by one (see the module doc). */
const KNOWN_INTERIOR_RESIDUAL = 24;

interface Case {
  readonly label: string;
  readonly scale: number;
  readonly src: RgbaBitmap;
  readonly expected: RgbaBitmap;
}

/** Java `getRGB` ints (`0xAARRGGBB`) -> RGBA bytes. */
function toRgba(hex: readonly string[], width: number, height: number): RgbaBitmap {
  const rgba = new Uint8Array(width * height * 4);
  hex.forEach((h, i) => {
    const argb = parseInt(h, 16) >>> 0;
    rgba.set([(argb >>> 16) & 255, (argb >>> 8) & 255, argb & 255, argb >>> 24], i * 4);
  });
  return { rgba, width, height };
}

function readCases(): Case[] {
  const lines = readFileSync(CASES, 'utf8').split('\n');
  const out: Case[] = [];
  for (let i = 0; i + 3 < lines.length; i += 4) {
    const [w, h, scale] = lines[i]!.split(' ').map(Number) as [number, number, number];
    const [dw, dh] = lines[i + 2]!.split(' ').map(Number) as [number, number];
    out.push({
      label: lines[i]!,
      scale,
      src: toRgba(lines[i + 1]!.trim().split(' '), w, h),
      expected: toRgba(lines[i + 3]!.trim().split(' '), dw, dh),
    });
  }
  return out;
}

function mismatches(actual: RgbaBitmap, expected: RgbaBitmap): { count: number; maxDelta: number } {
  let count = 0;
  let maxDelta = 0;
  expected.rgba.forEach((e, i) => {
    const d = Math.abs(e - actual.rgba[i]!);
    if (d !== 0) count++;
    maxDelta = Math.max(maxDelta, d);
  });
  return { count, maxDelta };
}

describe('scaleBilinear (PortableImageAwt#scale, TYPE_BILINEAR)', () => {
  const cases = readCases();

  it('reads all 21 reference cases', () => {
    expect(cases).toHaveLength(21);
  });

  it.each(cases.map((c) => [c.label, c] as const))('%s: raster size is round(w*s) x round(h*s)', (_, c) => {
    const out = scaleBilinear(c.src, c.scale);
    expect([out.width, out.height]).toEqual([c.expected.width, c.expected.height]);
  });

  it('matches the JDK on every channel but the recorded interior residual, each within 1', () => {
    let total = 0;
    let worst = 0;
    for (const c of cases) {
      const m = mismatches(scaleBilinear(c.src, c.scale), c.expected);
      total += m.count;
      worst = Math.max(worst, m.maxDelta);
    }
    expect(total).toBe(KNOWN_INTERIOR_RESIDUAL);
    expect(worst).toBe(1);
  });

  it('leaves destination pixels whose centre maps past the source transparent (3.7x of 7x5: row 18)', () => {
    const c = cases.find((k) => k.label === '7 5 3.7 5')!;
    const out = scaleBilinear(c.src, c.scale);
    const lastRow = out.rgba.subarray(18 * out.width * 4);
    expect([...lastRow].every((v) => v === 0)).toBe(true);
  });

  it('returns the source untouched at scale 1 (PortableImageAwt.java:114-115)', () => {
    const src = cases[0]!.src;
    expect(scaleBilinear(src, 1)).toBe(src);
  });

  it('sizes with Java Math.round, half up', () => {
    expect(scaledRasterSize(10, 12, 0.7)).toEqual({ width: 7, height: 8 });
    expect(scaledRasterSize(5, 5, 0.5)).toEqual({ width: 3, height: 3 });
  });
});
