@startuml
start
:a1;
    if (c1) then (Yes)
        :a2;
        end
    else (No)
        repeat
        :a3;
            if (c2) then (Yes)
                :a4;
                end
            else (No)
                if (c3) then (Yes)
                    :a5;
                else (No)
                    :a6;
                endif
                :a7;
            endif
        repeatwhile (r1)
        kill
    endif
@enduml
