@startmindmap
<style>
mindmapDiagram {
  FontColor blue
  FontStyle bold  
  FontSize 13

node {
  BackGroundColor palegreen
  LineThickness 1.0
}
  .red {
    FontColor red
    FontStyle bold  
    FontSize 13
    MaximumWidth 40
  }
}
</style>
+ the partner workpackage
++ blue
+++ blue workpackage
+++_ blue boxless workpackage 
++ red <<red>>
+++ red workpackage <<red>>
+++_ red boxless workpackage <<red>>

@endmindmap