/**
 * `skinparam dpi N` acceptance pin for the class engine (cdd-T30).
 *
 * `resolveScaleFactor`'s new `dpi` term (`core/scale-command.ts`,
 * `core/TextBlockExporter.java:205-209`) is now read from `theme.dpi` at
 * `layout.ts#layoutClass`'s EXISTING `resolveScaleFactor` call site — the
 * same call cdd-T29 wired for `scale ...`, widened, not a second scale-
 * resolution path. None of these five fixtures declares a `scale ...`
 * directive; the entire multiplier below comes from `dpi/96` alone
 * (`fromScale` defaults to 1 when `ast.scale` is `undefined`).
 *
 * Renders via `renderFixtureClass` + `DeterministicMeasurer` (the same
 * pipeline `class.golden.ratchet.test.ts` uses) against the jar-captured
 * `test-results/dot-cache/class/<slug>/in.svg` -- gitignored, regenerated by
 * `scripts/dot-sync-report.ts`/`scripts/capture-corpus.ts`; this suite
 * skips gracefully (not a failure) when the cache is absent, matching the
 * project's other dot-cache-dependent test conventions
 * (`description-doc-dims.test.ts`).
 *
 * Two of the five (`fuxoju-95-xuko052`, `bavoxa-34-keje375`) reach EXACT
 * (zero-diff) conformance and are asserted via full `compareSvg` equality.
 * `paluca-39-desa696` carries a residual this task's write-set does not
 * reach -- specific attributes this task's mechanism DOES control are
 * pinned directly instead of a whole-document compare.
 *
 * cdd-B8FU (`.agent-notes/cdd-B8FU.md`): `ziparo-17-joku307`'s
 * `class-visibility-icon.ts`/`renderer-note.ts` literals and
 * `kicuna-39-riki626`'s `renderer-arrowhead.ts#drawMiddleDecorShape`/
 * `class-namespace-shape.ts` package-tab literals (all named residuals in
 * `.agent-notes/cdd-T30.md`) are now threaded with `scaleK` -- their
 * `@stroke-width` structural diffs are zero (see each fixture's own test
 * below). Both fixtures still carry sub-pixel NUMERIC residuals outside
 * this task's mechanism (not asserted here, tracked in the agent notes).
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { DeterministicMeasurer } from '../../../src/core/measurer-deterministic.js';
import { compareSvg } from '../../oracle/svg-conformance/compare.js';
import { renderFixtureClass } from '../../oracle/svg-conformance/render-fixture-class.js';

function fixtureDir(slug: string): string {
  return join(process.cwd(), 'test-results', 'dot-cache', 'class', slug);
}

function readFixture(slug: string): { markup: string; oracle: string } {
  const dir = fixtureDir(slug);
  return {
    markup: readFileSync(join(dir, 'in.puml'), 'utf8'),
    oracle: readFileSync(join(dir, 'in.svg'), 'utf8'),
  };
}

function render(markup: string): string {
  return renderFixtureClass(markup, new DeterministicMeasurer());
}

const EXACT_SLUGS = ['fuxoju-95-xuko052', 'bavoxa-34-keje375'] as const;
const availableExact = EXACT_SLUGS.filter((slug) => existsSync(fixtureDir(slug)));

describe.skipIf(availableExact.length === 0)('layoutClass — dpi (exact-conformance fixtures)', () => {
  for (const slug of availableExact) {
    it(`class/${slug}: renders byte-identical (structural+numeric) to the jar's dpi-scaled in.svg`, () => {
      const { markup, oracle } = readFixture(slug);
      const ours = render(markup);
      const { pass, diffs } = compareSvg(ours, oracle, 'deterministic');
      expect(pass, `class/${slug}: first diff ${diffs[0] === undefined ? '(none)' : JSON.stringify(diffs[0])}`).toBe(
        true,
      );
    });
  }
});

describe.skipIf(!existsSync(fixtureDir('fuxoju-95-xuko052')))(
  'layoutClass — dpi 300, no scale directive (fuxoju-95-xuko052, class foo)',
  () => {
    it('scales font-size by exactly 300/96 = 3.125x (14 * 3.125 = 43.75)', () => {
      const { markup } = readFixture('fuxoju-95-xuko052');
      const ours = render(markup);
      expect(ours).toContain('font-size="43.75"');
    });
  },
);

describe.skipIf(!existsSync(fixtureDir('bavoxa-34-keje375')))(
  'layoutClass — dpi 200, no scale directive (bavoxa-34-keje375)',
  () => {
    it('scales every numeric by exactly 200/96 = 2.08(3)x (header 14 * 2.08333 = 29.167, body 12 * 2.08333 = 25)', () => {
      const { markup } = readFixture('bavoxa-34-keje375');
      const ours = render(markup);
      expect(ours).toContain('font-size="29.167"');
      expect(ours).toContain('font-size="25"');
      // classBorderStrokeWidth default 0.5 * 2.08333 = 1.042 (classifier box
      // rect); the composition-edge/qualifier-box stroke-width 1 * 2.08333
      // = 2.083 (class-scale-geo.ts / renderer-classifier-colors.ts, cdd-
      // T29's `ScaledTheme` thread).
      expect(ours).toContain('stroke-width="1.042"');
      expect(ours).toContain('stroke-width="2.083"');
    });
  },
);

describe.skipIf(!existsSync(fixtureDir('paluca-39-desa696')))(
  'layoutClass — dpi 300, no scale directive (paluca-39-desa696, class foo + realization)',
  () => {
    it('scales font-size and every classifier-box stroke-width by 3.125x', () => {
      const { markup } = readFixture('paluca-39-desa696');
      const ours = render(markup);
      expect(ours).toContain('font-size="43.75"');
      // classBorderStrokeWidth default 0.5*3.125=1.563 (classifier box rect
      // and member-section dividers), the classifier circle's default
      // 1*3.125=3.125, and the lollipop-interface circle's 1.5*3.125=4.688
      // (renderer-classifier-colors.ts / renderer-classifier-box.ts, cdd-
      // T29's `ScaledTheme` thread).
      expect(ours).toContain('stroke-width="1.563"');
      expect(ours).toContain('stroke-width="3.125"');
      expect(ours).toContain('stroke-width="4.688"');
    });
  },
);

describe.skipIf(!existsSync(fixtureDir('ziparo-17-joku307')))(
  'layoutClass — dpi 300, no scale directive (ziparo-17-joku307, class + notes + visibility icons)',
  () => {
    it('scales the classifier box, divider and note-box stroke-widths that cdd-T29 already threads scaleK through', () => {
      const { markup } = readFixture('ziparo-17-joku307');
      const ours = render(markup);
      expect(ours).toContain('font-size="43.75"');
      // classBorderStrokeWidth 0.5*3.125=1.563 (classifier box rect and
      // member-section dividers), the classifier circle's 1*3.125=3.125
      // (renderer-classifier-colors.ts/renderer-classifier-box.ts).
      expect(ours).toContain('stroke-width="1.563"');
      expect(ours).toContain('stroke-width="3.125"');
    });

    it('cdd-B8FU FIXED: the four member visibility-icon glyphs now scale (class-visibility-icon.ts:165 STROKE_WIDTH * theme.scaleK) -- zero structural stroke-width diffs remain', () => {
      const { markup, oracle } = readFixture('ziparo-17-joku307');
      const ours = render(markup);
      const { diffs } = compareSvg(ours, oracle, 'deterministic');
      // cdd-B8FU: was a NAMED residual (T30's own unscaled-1/-0.5 literals);
      // class-visibility-icon.ts / renderer-note.ts now thread scaleK, so
      // every stroke-width attribute matches the jar exactly (no structural
      // diff at all -- a numeric sub-pixel residual may remain elsewhere,
      // but never on @stroke-width).
      const structuralStrokeDiffs = diffs.filter((d) => d.delta === undefined && d.path.endsWith('@stroke-width'));
      expect(structuralStrokeDiffs).toHaveLength(0);
    });
  },
);

describe.skipIf(!existsSync(fixtureDir('kicuna-39-riki626')))(
  'layoutClass — dpi 300 + skinparam svek true (kicuna-39-riki626, package + aggregation edges)',
  () => {
    it('scales the classifier box stroke-width', () => {
      const { markup } = readFixture('kicuna-39-riki626');
      const ours = render(markup);
      expect(ours).toContain('font-size="43.75"');
    });

    it('cdd-B8FU FIXED: the aggregation diamond middleDecor stroke-width now scales (renderer-arrowhead.ts#drawMiddleDecorShape via SvgOption.scale) -- zero structural stroke-width diffs remain', () => {
      const { markup, oracle } = readFixture('kicuna-39-riki626');
      const ours = render(markup);
      const { diffs } = compareSvg(ours, oracle, 'deterministic');
      // cdd-B8FU: was a NAMED residual (T30's own unscaled MIDDLE_STROKE_WIDTH
      // 1.5); class-namespace-shape.ts's package-tab literals were the OTHER
      // half of this fixture's structural count (`package A { class B {} }`).
      const structuralStrokeDiffs = diffs.filter((d) => d.delta === undefined && d.path.endsWith('@stroke-width'));
      expect(structuralStrokeDiffs).toHaveLength(0);
    });
  },
);

if (availableExact.length === 0) {
  it('dot-cache/class is not populated locally — skipped gracefully (not a failure)', () => {
    expect(availableExact).toHaveLength(0);
  });
}
