/**
 * `skinparam dpi N` acceptance pin for the class engine (cdd-T30).
 *
 * `resolveScaleFactor`'s new `dpi` term (`core/scale-command.ts`,
 * `core/TextBlockExporter.java:205-209`) is now read from `theme.dpi` at
 * `layout.ts#layoutClass`'s EXISTING `resolveScaleFactor` call site — the
 * same call cdd-T29 wired for `scale ...`, widened, not a second scale-
 * resolution path. None of these five fixtures declares a `scale ...`
 * directive; the entire multiplier below comes from `dpi/96` alone
 * (`fromScale` defaults to 1 when `ast.scale` is `undefined`).
 *
 * Renders via `renderFixtureClass` + `DeterministicMeasurer` (the same
 * pipeline `class.golden.ratchet.test.ts` uses) against the jar-captured
 * `test-results/dot-cache/class/<slug>/in.svg` -- gitignored, regenerated by
 * `scripts/dot-sync-report.ts`/`scripts/capture-corpus.ts`; this suite
 * skips gracefully (not a failure) when the cache is absent, matching the
 * project's other dot-cache-dependent test conventions
 * (`description-doc-dims.test.ts`).
 *
 * Two of the five (`fuxoju-95-xuko052`, `bavoxa-34-keje375`) reach EXACT
 * (zero-diff) conformance and are asserted via full `compareSvg` equality.
 * The other three (`paluca-39-desa696`, `ziparo-17-joku307`,
 * `kicuna-39-riki626`) carry residuals this task's write-set does not
 * reach -- specific attributes this task's mechanism DOES control are
 * pinned directly instead of a whole-document compare; see
 * `.agent-notes/cdd-T30.md` for the residual mechanisms (each cited to its
 * own `file:line`, all pre-existing and outside T30's write-set: unscaled
 * literal constants in `class-visibility-icon.ts`, `renderer-note.ts`, and
 * `renderer-arrowhead.ts#drawMiddleDecorShape`).
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { DeterministicMeasurer } from '../../../src/core/measurer-deterministic.js';
import { compareSvg } from '../../oracle/svg-conformance/compare.js';
import { renderFixtureClass } from '../../oracle/svg-conformance/render-fixture-class.js';

function fixtureDir(slug: string): string {
  return join(process.cwd(), 'test-results', 'dot-cache', 'class', slug);
}

function readFixture(slug: string): { markup: string; oracle: string } {
  const dir = fixtureDir(slug);
  return {
    markup: readFileSync(join(dir, 'in.puml'), 'utf8'),
    oracle: readFileSync(join(dir, 'in.svg'), 'utf8'),
  };
}

function render(markup: string): string {
  return renderFixtureClass(markup, new DeterministicMeasurer());
}

const EXACT_SLUGS = ['fuxoju-95-xuko052', 'bavoxa-34-keje375'] as const;
const availableExact = EXACT_SLUGS.filter((slug) => existsSync(fixtureDir(slug)));

describe.skipIf(availableExact.length === 0)('layoutClass — dpi (exact-conformance fixtures)', () => {
  for (const slug of availableExact) {
    it(`class/${slug}: renders byte-identical (structural+numeric) to the jar's dpi-scaled in.svg`, () => {
      const { markup, oracle } = readFixture(slug);
      const ours = render(markup);
      const { pass, diffs } = compareSvg(ours, oracle, 'deterministic');
      expect(pass, `class/${slug}: first diff ${diffs[0] === undefined ? '(none)' : JSON.stringify(diffs[0])}`).toBe(
        true,
      );
    });
  }
});

describe.skipIf(!existsSync(fixtureDir('fuxoju-95-xuko052')))(
  'layoutClass — dpi 300, no scale directive (fuxoju-95-xuko052, class foo)',
  () => {
    it('scales font-size by exactly 300/96 = 3.125x (14 * 3.125 = 43.75)', () => {
      const { markup } = readFixture('fuxoju-95-xuko052');
      const ours = render(markup);
      expect(ours).toContain('font-size="43.75"');
    });
  },
);

describe.skipIf(!existsSync(fixtureDir('bavoxa-34-keje375')))(
  'layoutClass — dpi 200, no scale directive (bavoxa-34-keje375)',
  () => {
    it('scales every numeric by exactly 200/96 = 2.08(3)x (header 14 * 2.08333 = 29.167, body 12 * 2.08333 = 25)', () => {
      const { markup } = readFixture('bavoxa-34-keje375');
      const ours = render(markup);
      expect(ours).toContain('font-size="29.167"');
      expect(ours).toContain('font-size="25"');
      // classBorderStrokeWidth default 0.5 * 2.08333 = 1.042 (classifier box
      // rect); the composition-edge/qualifier-box stroke-width 1 * 2.08333
      // = 2.083 (class-scale-geo.ts / renderer-classifier-colors.ts, cdd-
      // T29's `ScaledTheme` thread).
      expect(ours).toContain('stroke-width="1.042"');
      expect(ours).toContain('stroke-width="2.083"');
    });
  },
);

describe.skipIf(!existsSync(fixtureDir('paluca-39-desa696')))(
  'layoutClass — dpi 300, no scale directive (paluca-39-desa696, class foo + realization)',
  () => {
    it('scales font-size and every classifier-box stroke-width by 3.125x', () => {
      const { markup } = readFixture('paluca-39-desa696');
      const ours = render(markup);
      expect(ours).toContain('font-size="43.75"');
      // classBorderStrokeWidth default 0.5*3.125=1.563 (classifier box rect
      // and member-section dividers), the classifier circle's default
      // 1*3.125=3.125, and the lollipop-interface circle's 1.5*3.125=4.688
      // (renderer-classifier-colors.ts / renderer-classifier-box.ts, cdd-
      // T29's `ScaledTheme` thread).
      expect(ours).toContain('stroke-width="1.563"');
      expect(ours).toContain('stroke-width="3.125"');
      expect(ours).toContain('stroke-width="4.688"');
    });
  },
);

describe.skipIf(!existsSync(fixtureDir('ziparo-17-joku307')))(
  'layoutClass — dpi 300, no scale directive (ziparo-17-joku307, class + notes + visibility icons)',
  () => {
    it('scales the classifier box, divider and note-box stroke-widths that cdd-T29 already threads scaleK through', () => {
      const { markup } = readFixture('ziparo-17-joku307');
      const ours = render(markup);
      expect(ours).toContain('font-size="43.75"');
      // classBorderStrokeWidth 0.5*3.125=1.563 (classifier box rect and
      // member-section dividers), the classifier circle's 1*3.125=3.125
      // (renderer-classifier-colors.ts/renderer-classifier-box.ts).
      expect(ours).toContain('stroke-width="1.563"');
      expect(ours).toContain('stroke-width="3.125"');
    });

    it('NAMED residual: the four member visibility-icon glyphs stay unscaled (class-visibility-icon.ts:165 STROKE_WIDTH=1, outside T30\'s write-set)', () => {
      const { markup, oracle } = readFixture('ziparo-17-joku307');
      const ours = render(markup);
      const { diffs } = compareSvg(ours, oracle, 'deterministic');
      const strokeDiffs = diffs.filter((d) => d.path.endsWith('@stroke-width'));
      // Every stroke-width residual is the SAME unscaled-1 visibility-icon
      // literal (expected 3.125 = 1 * dpi/96, actual 1) or the note-box's
      // unscaled 0.5 (expected 1.563 = 0.5 * dpi/96, actual 0.5) -- none is
      // a NEW divergence this task's own mechanism introduced.
      expect(strokeDiffs.length).toBeGreaterThan(0);
      for (const d of strokeDiffs) {
        expect([1, 0.5]).toContain(Number(d.actual));
      }
    });
  },
);

describe.skipIf(!existsSync(fixtureDir('kicuna-39-riki626')))(
  'layoutClass — dpi 300 + skinparam svek true (kicuna-39-riki626, package + aggregation edges)',
  () => {
    it('scales the classifier box stroke-width', () => {
      const { markup } = readFixture('kicuna-39-riki626');
      const ours = render(markup);
      expect(ours).toContain('font-size="43.75"');
    });

    it('NAMED residual: the aggregation diamond middleDecor stroke-width stays unscaled (renderer-arrowhead.ts:398 MIDDLE_STROKE_WIDTH=1.5, outside T30\'s write-set)', () => {
      const { markup, oracle } = readFixture('kicuna-39-riki626');
      const ours = render(markup);
      const { diffs } = compareSvg(ours, oracle, 'deterministic');
      const structuralStrokeDiffs = diffs.filter((d) => d.delta === undefined && d.path.endsWith('@stroke-width'));
      expect(structuralStrokeDiffs.length).toBeGreaterThan(0);
      for (const d of structuralStrokeDiffs) {
        expect(Number(d.actual)).toBe(1.5);
      }
    });
  },
);

if (availableExact.length === 0) {
  it('dot-cache/class is not populated locally — skipped gracefully (not a failure)', () => {
    expect(availableExact).toHaveLength(0);
  });
}
