@startmindmap
<style>
.test {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 1.0
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor green
  FontSize 11
  FontStyle bold
}
</style>
* a 
** b
** <<test9>>:b(Not yet ;-));
**: c
(OK); <<test>>
** d (OK) <<test>>
@endmindmap