/**
 * SName — every style-element name of `style/SName.java` (1.2026.8beta1),
 * the enum constant names verbatim (trailing underscores included:
 * `class_`, `goto_`, `interface_`, `package_`, `private_`, `protected_`,
 * `public_` -- Java keywords upstream escapes). Ported as a readonly
 * declaration-order array plus the string-literal union it induces (no
 * `const enum`, project convention). 157 constants, SName.java:42-202.
 *
 * Widened out of the 8-member consumed slice `StyleSignatureBasic.ts`
 * used to declare; that module now re-exports this type.
 *
 * @see ~/git/plantuml/src/main/java/net/sourceforge/plantuml/style/SName.java
 */
export const SNAMES = [
  'action',
  'activationBox',
  'activity',
  'activityBar',
  'activityDiagram',
  'actor',
  'agent',
  'analog',
  'archimate',
  'arrow',
  'artifact',
  'binary',
  'body',
  'boundary',
  'box',
  'boxless',
  'business',
  'caption',
  'card',
  'cardinality',
  'circle',
  'classDiagram',
  'class_',
  'clickable',
  'cloud',
  'closed',
  'collection',
  'collections',
  'component',
  'composite',
  'robust',
  'chenAttribute',
  'chenEerDiagram',
  'chenEntity',
  'chenRelationship',
  'concise',
  'clock',
  'componentDiagram',
  'constraintArrow',
  'control',
  'database',
  'day',
  'delay',
  'description',
  'destroy',
  'diamond',
  'document',
  'ebnf',
  'element',
  'entity',
  'end',
  'start',
  'stop',
  'file',
  'filesDiagram',
  'folder',
  'footer',
  'frame',
  'ganttDiagram',
  'generic',
  'goto_',
  'group',
  'groupHeader',
  'header',
  'hexagon',
  'highlight',
  'hnote',
  'interface_',
  'json',
  'jsonDiagram',
  'gitDiagram',
  'label',
  'leafNode',
  'legend',
  'lifeLine',
  'mainframe',
  'map',
  'milestone',
  'mindmapDiagram',
  'month',
  'name',
  'network',
  'newpage',
  'node',
  'note',
  'nwdiagDiagram',
  'packetdiagDiagram',
  'objectDiagram',
  'object',
  'package_',
  'participant',
  'partition',
  'person',
  'port',
  'process',
  'qualified',
  'queue',
  'rectangle',
  'reference',
  'referenceHeader',
  'regex',
  'requirement',
  'rnote',
  'root',
  'rootNode',
  'saltDiagram',
  'separator',
  'sequenceDiagram',
  'server',
  'stack',
  'stateDiagram',
  'state',
  'stateBody',
  'stereotype',
  'storage',
  'swimlane',
  'task',
  'timegrid',
  'timeline',
  'timingDiagram',
  'title',
  'undone',
  'unstarted',
  'usecase',
  'verticalSeparator',
  'year',
  'visibilityIcon',
  'private_',
  'protected_',
  'public_',
  'IEMandatory',
  'spot',
  'spotAnnotation',
  'spotInterface',
  'spotEnum',
  'spotProtocol',
  'spotStruct',
  'spotEntity',
  'spotException',
  'spotClass',
  'spotAbstractClass',
  'spotMetaClass',
  'spotStereotype',
  'spotDataClass',
  'spotRecord',
  'wbsDiagram',
  'yamlDiagram',
  'chartDiagram',
  'bar',
  'line',
  'area',
  'scatter',
  'axis',
  'hAxis',
  'vAxis',
  'grid',
  'annotation',
] as const;

/** One `SName.java` constant. @see SName.java:41-202 */
export type SName = (typeof SNAMES)[number];

/**
 * `SName.ALL` (SName.java:204-211): keyed by
 * `sname.name().replace("_", "").toLowerCase()`, filled in declaration
 * order (a later collision would win the `HashMap#put`; none exists).
 */
const ALL: ReadonlyMap<string, SName> = new Map(SNAMES.map((sname) => [sname.replace(/_/g, '').toLowerCase(), sname]));

/**
 * `SName.retrieve(String)` (SName.java:213-215): `ALL.get(s.toLowerCase())`,
 * `undefined` where upstream returns `null`.
 */
export function retrieve(s: string): SName | undefined {
  return ALL.get(s.toLowerCase());
}
