/**
 * Built-in PlantUML theme residue (amiga .. mono): only the fields an
 * executed `!theme` does not yet reach (json only) -- see scripts/compile-themes.py.
 * Auto-generated by scripts/compile-themes.py — do not edit by hand.
 * Re-run the script when upstream themes change.
 *
 * Split from themes-builtin.ts to stay under the 500-line-per-file cap;
 * themes-builtin.ts re-assembles BUILTIN_THEMES from this and its sibling
 * `themes-builtin-p-v.ts` in the original key order.
 */

import type { ThemeOverride } from './theme.js';

/** Partial Theme overrides for built-in PlantUML themes 'amiga' through 'mono'. */
export const BUILTIN_THEMES_A_M: Record<string, ThemeOverride> = {
  'amiga': {
    colors: {
      graph: {
        json: {
          background: '#0B58A8',
          border: '#FFFFFF',
          arrowColor: '#FFFFFF',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#0B58A8',
        },
      },
    },
  },
  'aws-orange': {
  },
  'black-knight': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'bluegray': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'blueprint': {
    colors: {
      graph: {
        json: {
          background: '#003153',
          border: '#D9D3D0',
          arrowColor: '#D9D3D0',
          keyText: '#D9D3D0',
          stringValue: '#D9D3D0',
          numberValue: '#D9D3D0',
          booleanValue: '#D9D3D0',
          nullValue: '#D9D3D0',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#003153',
        },
      },
    },
  },
  'carbon-gray': {
  },
  'cerulean-outline': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'cerulean': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'cloudscape-design': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'crt-amber': {
    colors: {
      graph: {
        json: {
          background: '#282828',
          border: '#FFB000',
          arrowColor: '#FFB000',
          keyText: '#FFB000',
          stringValue: '#FFB000',
          numberValue: '#FFB000',
          booleanValue: '#FFB000',
          nullValue: '#FFB000',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#282828',
        },
      },
    },
  },
  'crt-green': {
    colors: {
      graph: {
        json: {
          background: '#282828',
          border: '#33FF33',
          arrowColor: '#33FF33',
          keyText: '#33FF33',
          stringValue: '#33FF33',
          numberValue: '#33FF33',
          booleanValue: '#33FF33',
          nullValue: '#33FF33',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#282828',
        },
      },
    },
  },
  'cyborg-outline': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'cyborg': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'hacker': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'lightgray': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'mars': {
    colors: {
      graph: {
        json: {
          background: '#F9F9F9',
          border: '#191919',
          arrowColor: '#191919',
          keyText: '#191919',
          stringValue: '#191919',
          numberValue: '#191919',
          booleanValue: '#191919',
          nullValue: '#191919',
        },
      },
    },
  },
  'materia-outline': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'materia': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'metal': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'mimeograph': {
    colors: {
      graph: {
        json: {
          background: '#D9D3D0',
          border: '#9275B6',
          arrowColor: '#9275B6',
          keyText: '#9275B6',
          stringValue: '#9275B6',
          numberValue: '#9275B6',
          booleanValue: '#9275B6',
          nullValue: '#9275B6',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#D9D3D0',
        },
      },
    },
  },
  'minty': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'mono': {
    colors: {
      graph: {
        json: {
          background: 'white',
          border: 'black',
          arrowColor: 'black',
          keyText: 'black',
          stringValue: 'black',
          numberValue: 'black',
          booleanValue: 'black',
          nullValue: 'black',
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: 'white',
        },
      },
    },
  },
};
