/**
 * Built-in PlantUML theme definitions (plain .. vibrant).
 * Auto-generated by scripts/compile-themes.py — do not edit by hand.
 * Re-run the script when upstream themes change.
 *
 * Split from themes-builtin.ts to stay under the 500-line-per-file cap;
 * themes-builtin.ts re-assembles BUILTIN_THEMES from this and its sibling
 * `themes-builtin-a-m.ts` in the original key order.
 */

import type { ThemeOverride } from './theme.js';

/** Partial Theme overrides for built-in PlantUML themes 'plain' through 'vibrant'. */
export const BUILTIN_THEMES_P_V: Record<string, ThemeOverride> = {
  'plain': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 5, right: 5, bottom: 5, left: 5 },
    styleOverrides: {
      'document.caption': { linethickness: '0' },
      'document.footer': { linethickness: '0' },
      'document.header': { linethickness: '0' },
      'document.title': { fontsize: '22', linethickness: '0' },
      'root': { backgroundcolor: 'white', fontcolor: 'black', fontname: 'Verdana', hyperlinkcolor: 'blue', linecolor: 'black', linethickness: '1', margin: '5' },
    },
    colors: {
      background: 'white',
      text: 'black',
      border: 'black',
      arrow: 'black',
      graph: {
        json: {
          background: 'white',
          border: 'black',
          arrowColor: 'black',
          keyText: 'black',
          stringValue: 'black',
          numberValue: 'black',
          booleanValue: 'black',
          nullValue: 'black',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: 'white',
        },
      },
    },
  },
  'reddress-darkblue': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkgreen': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkorange': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkred': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-lightblue': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightgreen': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightorange': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightred': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'sandstone': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    styleOverrides: {
      'root': { backgroundcolor: 'transparent', fontcolor: '#fff', hyperlinkcolor: '#f47c3c', linecolor: '#2d547a', linethickness: '1', margin: '10', padding: '6', shadowing: '0.0' },
    },
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#2D547A',
      arrow: '#2D547A',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'silver': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    styleOverrides: {
      'root': { backgroundcolor: 'transparent', fontcolor: '#336699', hyperlinkcolor: '$ORANGE', linecolor: '#bebebe', linethickness: '1', margin: '10', padding: '6', shadowing: '0.0' },
    },
    colors: {
      background: 'transparent',
      text: '#336699',
      border: '#BEBEBE',
      arrow: '#BEBEBE',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'sketchy-outline': {
    fontFamily: 'Segoe Print',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    styleOverrides: {
      'root': { backgroundcolor: 'transparent', fontcolor: '#2e2e2e', hyperlinkcolor: '#fd7e14', linecolor: '#2e2e2e', linethickness: '1', margin: '10', padding: '6', shadowing: '0.0' },
    },
    colors: {
      background: 'transparent',
      text: '#2E2E2E',
      border: '#2E2E2E',
      arrow: '#2E2E2E',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'sketchy': {
    fontFamily: 'Segoe Print',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    styleOverrides: {
      'root': { backgroundcolor: 'transparent', fontcolor: '#ffffff', hyperlinkcolor: '#fd7e14', linecolor: '#2e2e2e', linethickness: '1', margin: '10', padding: '6', shadowing: '0.0' },
    },
    colors: {
      background: 'transparent',
      text: '#FFFFFF',
      border: '#2E2E2E',
      arrow: '#2E2E2E',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'spacelab-white': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    styleOverrides: {
      'root': { backgroundcolor: 'white', fontcolor: '#ffffff', hyperlinkcolor: '#fd7e14', linecolor: '#304d6d', linethickness: '1', margin: '10', padding: '6', shadowing: '0.0' },
    },
    colors: {
      background: 'white',
      text: '#FFFFFF',
      border: '#304D6D',
      arrow: '#304D6D',
      graph: {
        json: {
          background: 'white',
          border: '#304D6D',
          arrowColor: '#304D6D',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: 'white',
        },
      },
    },
  },
  'spacelab': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    styleOverrides: {
      'root': { backgroundcolor: 'transparent', fontcolor: '#ffffff', hyperlinkcolor: '#fd7e14', linecolor: '#304d6d', linethickness: '1', margin: '10', padding: '6', shadowing: '0.0' },
    },
    colors: {
      background: 'transparent',
      text: '#FFFFFF',
      border: '#304D6D',
      arrow: '#304D6D',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'sunlust': {
    fontFamily: 'Dejavu Serif',
    colors: {
      background: '#FDF6E3',
      text: '#657B83',
      border: '#657B83',
      arrow: '#657B83',
      graph: {
        json: {
          background: '#FDF6E3',
          border: '#657B83',
          arrowColor: '#657B83',
          keyText: '#657B83',
          stringValue: '#657B83',
          numberValue: '#657B83',
          booleanValue: '#657B83',
          nullValue: '#657B83',
        },
      },
    },
  },
  'superhero-outline': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    styleOverrides: {
      'root': { backgroundcolor: 'transparent', fontcolor: '#DF691A', hyperlinkcolor: '#f0ad4e', linecolor: '#e58748', linethickness: '1', margin: '10', padding: '6', shadowing: '0.0' },
    },
    colors: {
      background: 'transparent',
      text: '#DF691A',
      border: '#E58748',
      arrow: '#E58748',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'superhero': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    styleOverrides: {
      'root': { backgroundcolor: 'transparent', fontcolor: '#FFF', hyperlinkcolor: '#f0ad4e', linecolor: '#e58748', linethickness: '1', margin: '10', padding: '6', shadowing: '0.0' },
    },
    colors: {
      background: 'transparent',
      text: '#FFF',
      border: '#E58748',
      arrow: '#E58748',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'toy': {
    colors: {
      background: '#DDDDDD',
      text: '#333333',
      border: '#333333',
      arrow: '#333333',
      graph: {
        json: {
          background: '#DDDDDD',
          border: '#333333',
          arrowColor: '#333333',
          keyText: '#333333',
          stringValue: '#333333',
          numberValue: '#333333',
          booleanValue: '#333333',
          nullValue: '#333333',
        },
      },
    },
  },
  'united': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    styleOverrides: {
      'root': { backgroundcolor: 'transparent', fontcolor: '#fff', hyperlinkcolor: '#e95420', linecolor: '#d24c1d', linethickness: '1', margin: '10', padding: '6', shadowing: '0.0' },
    },
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#D24C1D',
      arrow: '#D24C1D',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'vibrant': {
    colors: {
      background: '#FFFFFF',
      text: '#333333',
      border: '#333333',
      arrow: '#333333',
      graph: {
        json: {
          background: '#FFFFFF',
          border: '#333333',
          arrowColor: '#333333',
          keyText: '#333333',
          stringValue: '#333333',
          numberValue: '#333333',
          booleanValue: '#333333',
          nullValue: '#333333',
        },
      },
    },
  },
};
