/**
 * Built-in PlantUML theme definitions (amiga .. mono).
 * Auto-generated by scripts/compile-themes.py — do not edit by hand.
 * Re-run the script when upstream themes change.
 *
 * Split from themes-builtin.ts to stay under the 500-line-per-file cap;
 * themes-builtin.ts re-assembles BUILTIN_THEMES from this and its sibling
 * `themes-builtin-p-v.ts` in the original key order.
 */

import type { ThemeOverride } from './theme.js';

/** Partial Theme overrides for built-in PlantUML themes 'amiga' through 'mono'. */
export const BUILTIN_THEMES_A_M: Record<string, ThemeOverride> = {
  'amiga': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 5, right: 5, bottom: 5, left: 5 },
    colors: {
      background: '#0B58A8',
      text: '#FFFFFF',
      border: '#FFFFFF',
      arrow: '#FFFFFF',
      graph: {
        json: {
          background: '#0B58A8',
          border: '#FFFFFF',
          arrowColor: '#FFFFFF',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#0B58A8',
        },
      },
    },
  },
  'aws-orange': {
    // R2j (mizupo-59): the upstream theme file sets `skinparam
    // defaultFontName "Verdana"` + `skinparam defaultFontSize 12`
    // (puml-theme-aws-orange.puml:195-196). compile-themes.py has no
    // FontSize extraction at all, so the two size fields are hand-carried
    // here until the script learns them (defaultFontSize doubles as the
    // explicit-set marker, see theme.ts#defaultFontSize).
    fontFamily: 'Verdana',
    fontSize: 12,
    defaultFontSize: 12,
    colors: {
      background: 'transparent',
      text: '#232F3E',
      border: '#FF9900',
      arrow: '#FF9900',
      graph: {
        // R2j: `skinparam class { AttributeFontSize 11 }`
        // (puml-theme-aws-orange.puml:446) -- member rows at 11pt, and the
        // class HEADER cascades to 11 too (no ClassFontSize in the theme;
        // the N32 attribute->header cascade, `theme-graph-colors-a.ts
        // #classAttributeFontSize`). Jar-verified via mizupo-59-zala765's
        // own golden: bare-class width = widthTable(name)@11 + 30.
        classAttributeFontSize: 11,
      },
    },
  },
  'black-knight': {
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#FFF200',
      border: '#1C1C1C',
      arrow: '#1C1C1C',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'bluegray': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#007FAF',
      arrow: '#007FAF',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'blueprint': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 5, right: 5, bottom: 5, left: 5 },
    colors: {
      background: '#003153',
      text: '#D9D3D0',
      border: '#D9D3D0',
      arrow: '#D9D3D0',
      graph: {
        json: {
          background: '#003153',
          border: '#D9D3D0',
          arrowColor: '#D9D3D0',
          keyText: '#D9D3D0',
          stringValue: '#D9D3D0',
          numberValue: '#D9D3D0',
          booleanValue: '#D9D3D0',
          nullValue: '#D9D3D0',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#003153',
        },
      },
    },
  },
  'carbon-gray': {
    fontFamily: 'IBM Plex Sans',
    colors: {
      background: 'transparent',
      text: '#F4F4F4',
      border: '#4D4D4D',
      arrow: '#4D4D4D',
    },
  },
  'cerulean-outline': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#2FA4E7',
      border: '#2683B9',
      arrow: '#2683B9',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'cerulean': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#FFF',
      border: '#2683B9',
      arrow: '#2683B9',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'cloudscape-design': {
    colors: {
      background: 'transparent',
      text: '#000716',
      border: '#0972D3',
      arrow: '#0972D3',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'crt-amber': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 5, right: 5, bottom: 5, left: 5 },
    colors: {
      background: '#282828',
      text: '#FFB000',
      border: '#FFB000',
      arrow: '#FFB000',
      graph: {
        json: {
          background: '#282828',
          border: '#FFB000',
          arrowColor: '#FFB000',
          keyText: '#FFB000',
          stringValue: '#FFB000',
          numberValue: '#FFB000',
          booleanValue: '#FFB000',
          nullValue: '#FFB000',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#282828',
        },
      },
    },
  },
  'crt-green': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 5, right: 5, bottom: 5, left: 5 },
    colors: {
      background: '#282828',
      text: '#33FF33',
      border: '#33FF33',
      arrow: '#33FF33',
      graph: {
        json: {
          background: '#282828',
          border: '#33FF33',
          arrowColor: '#33FF33',
          keyText: '#33FF33',
          stringValue: '#33FF33',
          numberValue: '#33FF33',
          booleanValue: '#33FF33',
          nullValue: '#33FF33',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#282828',
        },
      },
    },
  },
  'cyborg-outline': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#2A9FD6',
      border: '#55B2DE',
      arrow: '#55B2DE',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'cyborg': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#FFF',
      border: '#55B2DE',
      arrow: '#55B2DE',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'hacker': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#151515',
      border: '#6D8B32',
      arrow: '#6D8B32',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'lightgray': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#336699',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'mars': {
    colors: {
      background: '#F9F9F9',
      text: '#191919',
      border: '#191919',
      arrow: '#191919',
      graph: {
        json: {
          background: '#F9F9F9',
          border: '#191919',
          arrowColor: '#191919',
          keyText: '#191919',
          stringValue: '#191919',
          numberValue: '#191919',
          booleanValue: '#191919',
          nullValue: '#191919',
        },
      },
    },
  },
  'materia-outline': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#2196F3',
      border: '#1A78C2',
      arrow: '#1A78C2',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'materia': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#FFF',
      border: '#1A78C2',
      arrow: '#1A78C2',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'metal': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#4682B4',
      border: '#B7B6B5',
      arrow: '#B7B6B5',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'mimeograph': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 5, right: 5, bottom: 5, left: 5 },
    colors: {
      background: '#D9D3D0',
      text: '#9275B6',
      border: '#9275B6',
      arrow: '#9275B6',
      graph: {
        json: {
          background: '#D9D3D0',
          border: '#9275B6',
          arrowColor: '#9275B6',
          keyText: '#9275B6',
          stringValue: '#9275B6',
          numberValue: '#9275B6',
          booleanValue: '#9275B6',
          nullValue: '#9275B6',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: '#D9D3D0',
        },
      },
    },
  },
  'minty': {
    fontFamily: 'Verdana',
    diagramMargin: { top: 10, right: 10, bottom: 10, left: 10 },
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#6CAF9C',
      arrow: '#6CAF9C',
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'mono': {
    fontFamily: 'Hack',
    diagramMargin: { top: 5, right: 5, bottom: 5, left: 5 },
    colors: {
      background: 'white',
      text: 'black',
      border: 'black',
      arrow: 'black',
      graph: {
        json: {
          background: 'white',
          border: 'black',
          arrowColor: 'black',
          keyText: 'black',
          stringValue: 'black',
          numberValue: 'black',
          booleanValue: 'black',
          nullValue: 'black',
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: 'white',
        },
      },
    },
  },
};
