/**
 * Built-in PlantUML theme definitions.
 * Auto-generated by scripts/compile-themes.py — do not edit by hand.
 * Re-run the script when upstream themes change.
 *
 * The theme data itself is split across `themes-builtin-a-m.ts` (amiga..mono)
 * and `themes-builtin-p-v.ts` (plain..vibrant) to stay under the
 * 500-line-per-file cap. This module re-assembles BUILTIN_THEMES from those
 * two siblings in the original key order and remains the sole import site
 * used elsewhere in the codebase.
 */

import type { ThemeOverride } from './theme.js';
import { BUILTIN_THEMES_A_M } from './themes-builtin-a-m.js';
import { BUILTIN_THEMES_P_V } from './themes-builtin-p-v.js';

/** Partial Theme overrides for each built-in PlantUML theme name. */
export const BUILTIN_THEMES: Record<string, ThemeOverride> = {
  ...BUILTIN_THEMES_A_M,
  ...BUILTIN_THEMES_P_V,
};
