/**
 * Built-in PlantUML theme residue (plain .. vibrant): only the fields an
 * executed `!theme` does not yet reach (json only) -- see scripts/compile-themes.py.
 * Auto-generated by scripts/compile-themes.py — do not edit by hand.
 * Re-run the script when upstream themes change.
 *
 * Split from themes-builtin.ts to stay under the 500-line-per-file cap;
 * themes-builtin.ts re-assembles BUILTIN_THEMES from this and its sibling
 * `themes-builtin-a-m.ts` in the original key order.
 */

import type { ThemeOverride } from './theme.js';

/** Partial Theme overrides for built-in PlantUML themes 'plain' through 'vibrant'. */
export const BUILTIN_THEMES_P_V: Record<string, ThemeOverride> = {
  'plain': {
    colors: {
      graph: {
        json: {
          background: 'white',
          border: 'black',
          arrowColor: 'black',
          keyText: 'black',
          stringValue: 'black',
          numberValue: 'black',
          booleanValue: 'black',
          nullValue: 'black',
          maximumWidth: 300,
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: 'white',
        },
      },
    },
  },
  'reddress-darkblue': {
    colors: {
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkgreen': {
    colors: {
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkorange': {
    colors: {
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkred': {
    colors: {
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-lightblue': {
    colors: {
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightgreen': {
    colors: {
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightorange': {
    colors: {
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightred': {
    colors: {
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'sandstone': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'silver': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'sketchy-outline': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'sketchy': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'spacelab-white': {
    colors: {
      graph: {
        json: {
          background: 'white',
          border: '#304D6D',
          arrowColor: '#304D6D',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
          nodeLineThickness: 1,
          separatorThickness: 1,
          highlightBackground: 'white',
        },
      },
    },
  },
  'spacelab': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'sunlust': {
    colors: {
      graph: {
        json: {
          background: '#FDF6E3',
          border: '#657B83',
          arrowColor: '#657B83',
          keyText: '#657B83',
          stringValue: '#657B83',
          numberValue: '#657B83',
          booleanValue: '#657B83',
          nullValue: '#657B83',
        },
      },
    },
  },
  'superhero-outline': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'superhero': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'toy': {
    colors: {
      graph: {
        json: {
          background: '#DDDDDD',
          border: '#333333',
          arrowColor: '#333333',
          keyText: '#333333',
          stringValue: '#333333',
          numberValue: '#333333',
          booleanValue: '#333333',
          nullValue: '#333333',
        },
      },
    },
  },
  'united': {
    colors: {
      graph: {
        json: {
          nodeLineThickness: 1,
          separatorThickness: 1,
        },
      },
    },
  },
  'vibrant': {
    colors: {
      graph: {
        json: {
          background: '#FFFFFF',
          border: '#333333',
          arrowColor: '#333333',
          keyText: '#333333',
          stringValue: '#333333',
          numberValue: '#333333',
          booleanValue: '#333333',
          nullValue: '#333333',
        },
      },
    },
  },
};
