/**
 * Built-in PlantUML theme definitions (plain .. vibrant).
 * Auto-generated by scripts/compile-themes.py — do not edit by hand.
 * Re-run the script when upstream themes change.
 *
 * Split from themes-builtin.ts to stay under the 500-line-per-file cap;
 * themes-builtin.ts re-assembles BUILTIN_THEMES from this and its sibling
 * `themes-builtin-a-m.ts` in the original key order.
 */

import type { ThemeOverride } from './theme.js';

/** Partial Theme overrides for built-in PlantUML themes 'plain' through 'vibrant'. */
export const BUILTIN_THEMES_P_V: Record<string, ThemeOverride> = {
  'plain': {
    fontFamily: 'Verdana',
    colors: {
      background: 'white',
      text: 'black',
      border: 'black',
      arrow: 'black',
      graph: {
        json: {
          background: 'white',
          border: 'black',
          arrowColor: 'black',
          keyText: 'black',
          stringValue: 'black',
          numberValue: 'black',
          booleanValue: 'black',
          nullValue: 'black',
        },
      },
    },
  },
  'reddress-darkblue': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkgreen': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkorange': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkred': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-lightblue': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightgreen': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightorange': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightred': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'sandstone': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#2D547A',
      arrow: '#2D547A',
    },
  },
  'silver': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#336699',
      border: '#BEBEBE',
      arrow: '#BEBEBE',
    },
  },
  'sketchy-outline': {
    fontFamily: 'Segoe Print',
    colors: {
      background: 'transparent',
      text: '#2E2E2E',
      border: '#2E2E2E',
      arrow: '#2E2E2E',
    },
  },
  'sketchy': {
    fontFamily: 'Segoe Print',
    colors: {
      background: 'transparent',
      text: '#FFFFFF',
      border: '#2E2E2E',
      arrow: '#2E2E2E',
    },
  },
  'spacelab-white': {
    fontFamily: 'Verdana',
    colors: {
      background: 'white',
      text: '#FFFFFF',
      border: '#304D6D',
      arrow: '#304D6D',
      graph: {
        json: {
          background: 'white',
          border: '#304D6D',
          arrowColor: '#304D6D',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'spacelab': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#FFFFFF',
      border: '#304D6D',
      arrow: '#304D6D',
    },
  },
  'sunlust': {
    fontFamily: 'Dejavu Serif',
    colors: {
      background: '#FDF6E3',
      text: '#657B83',
      border: '#657B83',
      arrow: '#657B83',
      graph: {
        json: {
          background: '#FDF6E3',
          border: '#657B83',
          arrowColor: '#657B83',
          keyText: '#657B83',
          stringValue: '#657B83',
          numberValue: '#657B83',
          booleanValue: '#657B83',
          nullValue: '#657B83',
        },
      },
    },
  },
  'superhero-outline': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#DF691A',
      border: '#E58748',
      arrow: '#E58748',
    },
  },
  'superhero': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#FFF',
      border: '#E58748',
      arrow: '#E58748',
    },
  },
  'toy': {
    colors: {
      background: '#DDDDDD',
      text: '#333333',
      border: '#333333',
      arrow: '#333333',
      graph: {
        json: {
          background: '#DDDDDD',
          border: '#333333',
          arrowColor: '#333333',
          keyText: '#333333',
          stringValue: '#333333',
          numberValue: '#333333',
          booleanValue: '#333333',
          nullValue: '#333333',
        },
      },
    },
  },
  'united': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#D24C1D',
      arrow: '#D24C1D',
    },
  },
  'vibrant': {
    colors: {
      background: '#FFFFFF',
      text: '#333333',
      border: '#333333',
      arrow: '#333333',
      graph: {
        json: {
          background: '#FFFFFF',
          border: '#333333',
          arrowColor: '#333333',
          keyText: '#333333',
          stringValue: '#333333',
          numberValue: '#333333',
          booleanValue: '#333333',
          nullValue: '#333333',
        },
      },
    },
  },
};
