/**
 * Generates `src/core/themes-source.ts`: upstream's bundled theme files,
 * VERBATIM, keyed by theme name -- the text `ThemeUtils#loadBundledOrLocalTheme`
 * reads from the jar's `/themes/puml-theme-<name>.puml` resources
 * (`ThemeUtils.java:131-139`). Browser-safe `src/` has no filesystem, so the
 * resources are embedded as string literals, exactly as upstream's own browser
 * build ships them in `themes.js` (`ThemeUtils.java:84-117`, `loadJsTheme`).
 *
 * One property per theme, laid out exactly as Prettier prints it (key on its
 * own line, bare when identifier-safe; the literal in `.prettierrc`'s single
 * quote unless the text holds more single quotes than double), so the
 * pre-commit Prettier pass leaves the generated file byte-identical. 44 themes
 * stay far under the 500-line file cap.
 *
 *   npx jiti scripts/build-theme-sources.ts           regenerate
 *   npx jiti scripts/build-theme-sources.ts --check   exit 1 if it would change
 *
 * Drift gate: `tests/unit/core/themes-source.test.ts`.
 *
 * Node-only dev tooling -- never imported by `src/`.
 *
 * @see ~/git/plantuml/src/main/java/net/sourceforge/plantuml/theme/ThemeUtils.java
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Upstream's theme resource folder (`ThemeUtils.java` `THEME_PATH = "themes"`). */
export const UPSTREAM_THEMES_DIR = join(homedir(), 'git', 'plantuml', 'src', 'main', 'resources', 'themes');

export const THEME_SOURCES_PATH = join(REPO, 'src', 'core', 'themes-source.ts');

/** `ThemeUtils.java` `THEME_FILE_PREFIX` / `THEME_FILE_SUFFIX`. */
const THEME_FILE_PREFIX = 'puml-theme-';
const THEME_FILE_SUFFIX = '.puml';

/**
 * Every `puml-theme-<name>.puml` in `dir`, keyed by `<name>`, sorted by name --
 * the filter `ThemeUtils#getAllThemeNames` applies (`ThemeUtils.java:181-184`).
 */
export function readThemeSources(dir: string = UPSTREAM_THEMES_DIR): ReadonlyMap<string, string> {
  const names = readdirSync(dir)
    .filter((f) => f.startsWith(THEME_FILE_PREFIX) && f.endsWith(THEME_FILE_SUFFIX))
    .map((f) => f.slice(THEME_FILE_PREFIX.length, f.length - THEME_FILE_SUFFIX.length))
    .sort();
  return new Map(
    names.map((name) => [name, readFileSync(join(dir, `${THEME_FILE_PREFIX}${name}${THEME_FILE_SUFFIX}`), 'utf8')]),
  );
}

/** Escapes that JavaScript requires inside a quoted literal. */
const ESCAPES: Readonly<Record<string, string>> = { '\\': '\\\\', '\n': '\\n', '\r': '\\r', '\t': '\\t' };

/** Control characters other than the three with short escapes. */
const RE_CONTROL = /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/u;

/** Prettier's quote choice: the preferred (single) quote unless the text holds more of it. */
function quoteFor(text: string): string {
  const singles = text.split("'").length - 1;
  const doubles = text.split('"').length - 1;
  return singles > doubles ? '"' : "'";
}

/** A JS string literal for `text`, in the quote Prettier would choose. */
export function toStringLiteral(text: string): string {
  const quote = quoteFor(text);
  let body = '';
  for (const ch of text) {
    if (ch === quote) body += `\\${ch}`;
    else if (ESCAPES[ch] !== undefined) body += ESCAPES[ch];
    else if (RE_CONTROL.test(ch)) body += `\\u${ch.charCodeAt(0).toString(16).padStart(4, '0')}`;
    else body += ch;
  }
  return `${quote}${body}${quote}`;
}

const HEADER = `/**
 * GENERATED by \`scripts/build-theme-sources.ts\` -- do not edit by hand.
 *
 * Upstream's bundled theme files, verbatim, keyed by theme name: the
 * \`/themes/puml-theme-<name>.puml\` resources \`ThemeUtils#loadBundledOrLocalTheme\`
 * reads (\`ThemeUtils.java:131-139\`). Embedded because browser-safe \`src/\` has
 * no filesystem -- upstream's browser build ships the same texts in
 * \`themes.js\` (\`ThemeUtils.java:84-117\`). Look a theme up with
 * \`Object.hasOwn\`, never a bare index: a name such as \`constructor\` must miss.
 *
 * @see ~/git/plantuml/src/main/resources/themes/
 * @see ~/git/plantuml/src/main/java/net/sourceforge/plantuml/theme/ThemeUtils.java
 */
`;

/** An identifier-safe key stays bare, as Prettier's `quoteProps: as-needed` leaves it. */
const RE_BARE_KEY = /^[A-Za-z_$][\w$]*$/u;

/**
 * Prettier keeps a value on its key's line when the key prints narrower than
 * `tabWidth + MIN_OVERLAP_FOR_BREAK` (2 + 3; `isObjectPropertyWithShortKey` in
 * Prettier's assignment layout) and breaks after the colon otherwise.
 */
const SHORT_KEY_WIDTH = 5;

/** The module text for `sources` -- pure, so the drift test can call it. */
export function renderThemeSourcesModule(sources: ReadonlyMap<string, string>): string {
  const props = [...sources].map(([name, text]) => {
    const key = RE_BARE_KEY.test(name) ? name : toStringLiteral(name);
    const gap = key.length < SHORT_KEY_WIDTH ? ' ' : '\n    ';
    return `  ${key}:${gap}${toStringLiteral(text)},`;
  });
  return `${HEADER}\nexport const THEME_SOURCES: Readonly<Record<string, string>> = {\n${props.join('\n')}\n};\n`;
}

function main(): void {
  const themes = readThemeSources();
  const body = renderThemeSourcesModule(themes);
  if (process.argv.includes('--check')) {
    const current = existsSync(THEME_SOURCES_PATH) ? readFileSync(THEME_SOURCES_PATH, 'utf8') : '';
    if (current !== body) {
      console.error('src/core/themes-source.ts is out of date -- run `npx jiti scripts/build-theme-sources.ts`.');
      process.exit(1);
    }
    console.log('src/core/themes-source.ts is up to date.');
    return;
  }
  writeFileSync(THEME_SOURCES_PATH, body);
  console.log(`[themes] wrote ${String(themes.size)} themes to src/core/themes-source.ts`);
}

// CLI only: importing this module (the drift test does) must have no side effect.
if (process.argv[1]?.endsWith('build-theme-sources.ts') === true) main();
