/**
 * `--probe-json-dot` — one-shot probe: does `-DPLANTUML_DUMP_DOT` produce
 * svek-*.dot for json/dot fixtures? Split out of `dot-sync-report.ts` (mission
 * parity-dashboard-refresh, T6) when adding the `--json` CLI hook pushed that
 * file past the 500-line complexity cap. This probe has no callers elsewhere
 * and is a self-contained diagnostic, making it the natural piece to extract.
 *
 * `plantumlDots`/`CACHE` are imported back from `dot-sync-report.ts` rather
 * than duplicated — same circular-import shape as `dot-parity-rows.ts` (see
 * that module's header comment for why a parameter default, not a top-level
 * constant, is the way this kind of cross-import stays safe).
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { enumerateFixtures } from './dot-sync-fixtures.js';
import { plantumlDots } from './dot-sync-report.js';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const PROBE_OUT = join(REPO, 'plans', 'dot-oracle-sync', 'phase-5-json-dot', 'probe.md');

interface ProbeResult {
  anyDots: boolean;
  evidence: string[];
}

function probeType(jar: string, type: string): ProbeResult | undefined {
  const fixtures = enumerateFixtures(type);
  if (fixtures === undefined) return undefined;
  const sample = [...fixtures].sort((a, b) => a.slug.localeCompare(b.slug)).slice(0, 5);
  const evidence: string[] = [];
  let anyDots = false;
  for (const f of sample) {
    const dots = plantumlDots(jar, type, f, false);
    evidence.push(f.slug + ': ' + dots.length + ' svek-*.dot file(s)');
    if (dots.length > 0) anyDots = true;
  }
  return { anyDots, evidence };
}

function jsonImplication(anyDots: boolean): string {
  if (anyDots) {
    return 'svek-*.dot appeared for at least one json fixture, contradicting the phase-5 assumption that @startjson routes through SmetanaForJson directly — worth investigating whether this is loopable via the standard svek oracle after all.';
  }
  return 'No svek-*.dot appeared for any sampled json fixture, consistent with the phase-5 expectation that @startjson uses SmetanaForJson directly rather than routing through svek DOT. Per the overview this means json (and transitively yaml/hcl) is not loopable via the existing svek StructuralDiff oracle and needs a maintainer decision: treat as out of scope for this mission, or define a new Smetana-input oracle. Do not invent one without sign-off — this is a STOP condition.';
}

function dotImplication(anyDots: boolean): string {
  if (anyDots) {
    return "svek-*.dot appeared for at least one dot fixture, contradicting the phase-5 assumption that @startdot feeds the fixture's own DOT straight to graphviz — worth confirming before assuming the fixture body itself is the oracle.";
  }
  return "No svek-*.dot appeared for any sampled dot fixture, consistent with the phase-5 expectation that @startdot passes the fixture's own DOT body verbatim to graphviz with no svek intermediate. Per the overview, the oracle for this type is the fixture's own DOT text, and parity should be defined as \"does the seam's DotInputGraph preserve the input graph\" — a new comparison, not the svek StructuralDiff. That needs a short design note and maintainer sign-off (STOP condition) before looping.";
}

function probeSection(
  type: string,
  result: ProbeResult | undefined,
  implication: (anyDots: boolean) => string,
): string[] {
  const lines: string[] = ['## ' + type, ''];
  if (result === undefined) {
    lines.push(
      'Verdict: no fixture manifest — tests/visual/data/' + type + '.json does not exist.',
      '',
      'Evidence: none (no fixtures could be sampled).',
      '',
    );
    return lines;
  }
  lines.push(
    'Verdict: svek dump path ' +
      (result.anyDots ? 'EXISTS' : 'DOES NOT EXIST') +
      ' for ' +
      type +
      ' (' +
      (result.anyDots ? 'at least one' : 'none of the') +
      ' sampled fixtures produced svek-*.dot).',
    '',
    'Evidence:',
  );
  for (const e of result.evidence) lines.push('- ' + e);
  lines.push('', 'Implication: ' + implication(result.anyDots), '');
  return lines;
}

/** One-line verdict summary for the probe's stdout tail. */
function probeVerdictLine(label: string, result: ProbeResult | undefined): string {
  const verdict =
    result === undefined ? 'no manifest' : result.anyDots ? 'svek dump EXISTS' : 'svek dump DOES NOT EXIST';
  return label + ': ' + verdict;
}

export function runProbeJsonDot(jar: string): void {
  const jsonResult = probeType(jar, 'json');
  const dotResult = probeType(jar, 'dot');
  const lines: string[] = [
    '# Phase 5 probe — json/dot svek DOT dump',
    '',
    'Generated by npx tsx scripts/dot-sync-report.ts --probe-json-dot.',
    '',
    ...probeSection('json', jsonResult, jsonImplication),
    ...probeSection('dot', dotResult, dotImplication),
  ];
  mkdirSync(dirname(PROBE_OUT), { recursive: true });
  writeFileSync(PROBE_OUT, lines.join('\n') + '\n', 'utf-8');
  console.log('Wrote ' + PROBE_OUT);
  console.log(probeVerdictLine('json', jsonResult));
  console.log(probeVerdictLine('dot ', dotResult));
}
