/**
 * Generates `src/core/style/skins/plantuml-skin.ts`: the `skin/*.skin`
 * entries from the oracle jar (`oracle/dist/plantuml-oracle.jar`) that
 * `StyleLoader.loadSkin` can actually reach, embedded verbatim as string
 * constants -- browser-safe `src/` has no filesystem, so a `.skin` resource
 * that upstream reads from disk/jar at runtime must ship as source text
 * here instead (mirrors `build-theme-sources.ts`'s approach for
 * `themes-source.ts`, one directory up).
 *
 * Which entries (T0d D1, decision-journal.md):
 *
 *  - `plantuml.skin` -- `SkinParam.DEFAULT_SKIN` (SkinParam.java:126:
 *    `public static final String DEFAULT_SKIN = "plantuml.skin";`), loaded
 *    by `StyleLoader.loadSkin` (StyleLoader.java:65-108) whenever no
 *    explicit `skin <name>` directive overrides it -- every diagram's
 *    default style sheet.
 *  - `strictuml.skin` -- loaded by `SkinParam.setParam` when `skinparam
 *    style strictuml` is set (SkinParam.java:236-247: `if
 *    ("style".equalsIgnoreCase(key) && "strictuml".equalsIgnoreCase(value))
 *    ... StyleLoader.class.getResourceAsStream("/skin/strictuml.skin")`),
 *    muted on top of the current style builder rather than replacing it
 *    (StyleLoader.java:145-160's `MANDATORY_ROOT_PROPERTIES` doc: strictuml
 *    is deliberately a fragment, not a complete sheet).
 *
 * `debug.skin`, `rose.skin`, and `sonyxperiadev.skin` are reachable only
 * via an explicit `skin <name>` directive (`SkinParam.setDefaultSkin`,
 * `StyleLoader.getInputStreamForStyle`'s `/skin/" + filename` fallback);
 * none of the 125 mindmap corpus fixtures (`~/git/pdiff/**\/*.puml` with
 * `@startmindmap`) uses `skin <name>` or `skinparam style strictuml` (grep
 * confirmed empty), so they are out of scope here -- add them when a
 * fixture or a later task's `skin <name>` support needs them.
 *
 *   npx jiti scripts/extract-jar-skin.ts           regenerate
 *   npx jiti scripts/extract-jar-skin.ts --check   exit 1 if it would change
 *
 * Drift gate: `tests/unit/core/style/plantuml-skin-drift.test.ts`.
 *
 * Node-only dev tooling -- never imported by `src/`.
 *
 * @see ~/git/plantuml/src/main/java/net/sourceforge/plantuml/style/StyleLoader.java
 * @see ~/git/plantuml/src/main/java/net/sourceforge/plantuml/skin/SkinParam.java
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { toStringLiteral } from './build-theme-sources.js';
import { readZipEntries } from './lib/jar-zip-reader.js';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');

/** The oracle jar (1.2026.8beta1, per `oracle-render.sh`/T0c's probes). */
export const ORACLE_JAR_PATH = join(REPO, 'oracle', 'dist', 'plantuml-oracle.jar');

export const PLANTUML_SKIN_PATH = join(REPO, 'src', 'core', 'style', 'skins', 'plantuml-skin.ts');

const MANIFEST_ENTRY = 'META-INF/MANIFEST.MF';

/** Skin entries `StyleLoader.loadSkin` can reach from the mindmap corpus (see header). */
export const SKIN_EXPORTS: ReadonlyArray<{ readonly entry: string; readonly exportName: string }> = [
  { entry: 'skin/plantuml.skin', exportName: 'PLANTUML_SKIN' },
  { entry: 'skin/strictuml.skin', exportName: 'STRICTUML_SKIN' },
];

export interface SkinSource {
  readonly entry: string;
  readonly exportName: string;
  readonly text: string;
  readonly sha256: string;
}

export interface SkinSources {
  readonly jarVersion: string;
  readonly skins: readonly SkinSource[];
}

/** The jar's `Implementation-Version` (`META-INF/MANIFEST.MF`), e.g. `1.2026.8beta1`. */
function parseJarVersion(manifest: Buffer): string {
  const version = /Implementation-Version:\s*(\S+)/.exec(manifest.toString('utf8'))?.[1];
  if (version === undefined) throw new Error(`${MANIFEST_ENTRY}: Implementation-Version not found`);
  return version;
}

/** Reads `SKIN_EXPORTS`' entries (plus the manifest, for the version) out of `jarPath`. */
export function readSkinSources(jarPath: string = ORACLE_JAR_PATH): SkinSources {
  const names = [MANIFEST_ENTRY, ...SKIN_EXPORTS.map((s) => s.entry)];
  const entries = readZipEntries(jarPath, names);
  const manifest = entries.get(MANIFEST_ENTRY);
  if (manifest === undefined) throw new Error(`${MANIFEST_ENTRY} not found in ${jarPath}`);
  const skins = SKIN_EXPORTS.map(({ entry, exportName }) => {
    const buf = entries.get(entry);
    if (buf === undefined) throw new Error(`${entry} not found in ${jarPath}`);
    return { entry, exportName, text: buf.toString('utf8'), sha256: createHash('sha256').update(buf).digest('hex') };
  });
  return { jarVersion: parseJarVersion(manifest), skins };
}

const HEADER_INTRO = `/**
 * GENERATED by \`scripts/extract-jar-skin.ts\` -- do not edit by hand.
 *
 * Verbatim \`skin/*.skin\` entries from the oracle jar
 * (\`oracle/dist/plantuml-oracle.jar\`), reachable via \`StyleLoader.loadSkin\`
 * -- see this file's header comment for which entries and why.
 *`;

const HEADER_OUTRO = ` *
 * @see ~/git/plantuml/src/main/java/net/sourceforge/plantuml/style/StyleLoader.java
 * @see ~/git/plantuml/src/main/java/net/sourceforge/plantuml/skin/SkinParam.java
 */
`;

/** Version + one sha256 line per entry, sandwiched between the static intro/outro. */
function renderHeader({ jarVersion, skins }: SkinSources): string {
  const version = ` * Implementation-Version ${jarVersion}.`;
  const hashLines = skins.map((s) => ` *   ${s.entry.padEnd(20)} sha256:${s.sha256}`).join('\n');
  return [HEADER_INTRO, version, hashLines, HEADER_OUTRO].join('\n');
}

/** `.prettierrc.json`'s `printWidth` -- the generator must match Prettier's own line-break choice. */
const PRINT_WIDTH = 120;

/** `export const NAME = "literal";`, broken after `=` exactly as Prettier would if it doesn't fit. */
function renderExport(name: string, literal: string): string {
  const oneLine = `export const ${name} = ${literal};`;
  return oneLine.length <= PRINT_WIDTH ? oneLine : `export const ${name} =\n  ${literal};`;
}

/** The module text for `sources` -- pure, so the drift test can call it. */
export function renderSkinModule(sources: SkinSources): string {
  const versionExport = renderExport('SKIN_JAR_VERSION', toStringLiteral(sources.jarVersion));
  const skinExports = sources.skins.map((s) => renderExport(s.exportName, toStringLiteral(s.text)));
  return `${renderHeader(sources)}\n${[versionExport, ...skinExports].join('\n\n')}\n`;
}

function main(): void {
  const sources = readSkinSources();
  const body = renderSkinModule(sources);
  if (process.argv.includes('--check')) {
    const current = existsSync(PLANTUML_SKIN_PATH) ? readFileSync(PLANTUML_SKIN_PATH, 'utf8') : '';
    if (current !== body) {
      console.error(
        'src/core/style/skins/plantuml-skin.ts is out of date -- run `npx jiti scripts/extract-jar-skin.ts`.',
      );
      process.exit(1);
    }
    console.log('src/core/style/skins/plantuml-skin.ts is up to date.');
    return;
  }
  mkdirSync(dirname(PLANTUML_SKIN_PATH), { recursive: true });
  writeFileSync(PLANTUML_SKIN_PATH, body);
  console.log(`[skin] wrote ${String(sources.skins.length)} skins to src/core/style/skins/plantuml-skin.ts`);
}

// CLI only: importing this module (the drift test does) must have no side effect.
if (process.argv[1]?.endsWith('extract-jar-skin.ts') === true) main();
