/**
 * SI12 T1 -- the generator stops EMITTING eager modules for `stdlib-aws` and
 * `stdlib-tupadr3` (`plans/si12-eager-module-removal/batch-1/T1-generator-omits-eager.md`,
 * ADR-1/ADR-2/ADR-5).
 *
 * `packages/*\/generated/` is built ONCE by vitest's globalSetup
 * (`tests/helpers/build-stdlib-globalsetup.ts`), not here -- rebuilding it in
 * a per-file `beforeAll` races the other test files reading the same tree
 * (`tests/unit/stdlib-packages.test.ts` documents the failure mode). Every
 * assertion below reads bytes already on disk.
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { withStdlibBuildLock } from '../helpers/with-stdlib-build-lock.js';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const PACKAGES_DIR = join(REPO_ROOT, 'packages');

function sha256Hex(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

function generatedPath(packageDir: string, fileName: string): string {
  return join(PACKAGES_DIR, packageDir, 'generated', fileName);
}

// stdlib-run-isolation T4 (option D): every read of `generated/` in this
// file is a single, hardcoded-filename fs call -- no `readdirSync`, so
// there is no readdir-then-read window to keep atomic (contrast
// `stdlib-dts-import-specifier.test.ts`). Each of the three accessors below
// is therefore self-locking, held for exactly its own call.

function readGeneratedText(packageDir: string, fileName: string): string {
  return withStdlibBuildLock(() => readFileSync(generatedPath(packageDir, fileName), 'utf8'));
}

function readGeneratedBytes(packageDir: string, fileName: string): Buffer {
  return withStdlibBuildLock(() => readFileSync(generatedPath(packageDir, fileName)));
}

function generatedExists(packageDir: string, fileName: string): boolean {
  return withStdlibBuildLock(() => existsSync(generatedPath(packageDir, fileName)));
}

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/build-stdlib-packages.ts -- DO NOT EDIT.\n' +
  '// Regenerate with: npm run build:stdlib\n';

// ---------------------------------------------------------------------------
// Acceptance 1: no eager module file, `generated/index.js` re-exports the
// remote manifest bindings instead (ADR-1).
// ---------------------------------------------------------------------------

describe('acceptance 1: stdlib-aws ships no eager module', () => {
  const EXPECTED_INDEX =
    GENERATED_HEADER +
    '\n' +
    "export { awslib14Remote } from './awslib14.remote.js';\n" +
    "export { awslibRemote } from './awslib.remote.js';\n";

  it('generated/index.js re-exports awslib14Remote and awslibRemote', () => {
    const indexJs = readGeneratedText('stdlib-aws', 'index.js');
    expect(indexJs).toBe(EXPECTED_INDEX);
  },
    120_000);

  it('generated/index.d.ts re-exports the same bindings', () => {
    const indexDts = readGeneratedText('stdlib-aws', 'index.d.ts');
    expect(indexDts).toBe(EXPECTED_INDEX);
  },
    120_000);

  it('awslib14.js and awslib.js are not emitted', () => {
    expect(generatedExists('stdlib-aws', 'awslib14.js')).toBe(false);
    expect(generatedExists('stdlib-aws', 'awslib.js')).toBe(false);
    expect(generatedExists('stdlib-aws', 'awslib14.d.ts')).toBe(false);
    expect(generatedExists('stdlib-aws', 'awslib.d.ts')).toBe(false);
  },
    120_000);

  it('the remote manifest siblings are emitted instead', () => {
    expect(generatedExists('stdlib-aws', 'awslib14.remote.js')).toBe(true);
    expect(generatedExists('stdlib-aws', 'awslib.remote.js')).toBe(true);
  },
    120_000);
});

describe('acceptance 1: stdlib-tupadr3 ships no eager module', () => {
  const EXPECTED_INDEX = GENERATED_HEADER + '\n' + "export { tupadr3Remote } from './tupadr3.remote.js';\n";

  it('generated/index.js re-exports tupadr3Remote', () => {
    const indexJs = readGeneratedText('stdlib-tupadr3', 'index.js');
    expect(indexJs).toBe(EXPECTED_INDEX);
  },
    120_000);

  it('generated/index.d.ts re-exports the same binding', () => {
    const indexDts = readGeneratedText('stdlib-tupadr3', 'index.d.ts');
    expect(indexDts).toBe(EXPECTED_INDEX);
  },
    120_000);

  it('tupadr3.js is not emitted', () => {
    expect(generatedExists('stdlib-tupadr3', 'tupadr3.js')).toBe(false);
    expect(generatedExists('stdlib-tupadr3', 'tupadr3.d.ts')).toBe(false);
  },
    120_000);

  it('the remote manifest sibling is emitted instead', () => {
    expect(generatedExists('stdlib-tupadr3', 'tupadr3.remote.js')).toBe(true);
  },
    120_000);
});

// ---------------------------------------------------------------------------
// Acceptance 2: packages/stdlib's five eager modules stay byte-identical.
// Digests pinned from the pre-SI12 tree
// (`plans/si12-eager-module-removal/batch-1/T1-generator-omits-eager.md`).
//
// The five `.js` digests are the ORIGINAL pre-SI12 values and must not move:
// they cover the inlined `.puml` content, which no change here may re-encode.
//
// The five bundle `.d.ts` digests were RE-PINNED once, deliberately, after
// SI12 closed: fixing the generated import specifier from the pre-scope
// `'plantuml-ts'` to the declared `'@knowvah/plantuml-ts'` changes exactly
// one line of every `.d.ts` and nothing else. That this guard fired on those
// five files and on NOTHING else -- not one `.js`, not `index.d.ts`, which
// has no bare import -- is the evidence the fix was as narrow as claimed.
// See `tests/unit/stdlib-dts-import-specifier.test.ts` for why the specifier
// was wrong and why no gate caught it.
// ---------------------------------------------------------------------------

interface PinnedFile {
  readonly fileName: string;
  readonly sha256: string;
}

const STDLIB_PINNED_DIGESTS: readonly PinnedFile[] = [
  { fileName: 'archimate.d.ts', sha256: '854c36873a504bcb2722cb8825de7ed536647ec4fa0eae729a59410d691821f5' },
  { fileName: 'archimate.js', sha256: '2b7cc62394934490272f23307517ed21b05c4534f92758369bf2d7ec0e08878f' },
  { fileName: 'bootstrap.d.ts', sha256: 'eae58032689977aa6307e4d805affc1c604d0ab81f91d855c546bc65419ade37' },
  { fileName: 'bootstrap.js', sha256: '29fefcebde1e4896d5687c8ad1fc57213e9d2690213048d899846d0de392ea5f' },
  { fileName: 'c4.d.ts', sha256: '05d164a72731551a3af48dba27ef1999c6be0f902a38032eec1dd5d446744d4f' },
  { fileName: 'c4.js', sha256: 'f7929a5a2efdfd453e7889677ffc89f3fd050a4915139f2149838c8fd65cb0c7' },
  { fileName: 'cloudinsight.d.ts', sha256: '17127c221eed82136e5b9d302123f6e9e9568d2a1a911a0b658e624bd6f9ed51' },
  { fileName: 'cloudinsight.js', sha256: '26edf20eef9bc3b79bd8affdc1d2f16f2ffa3ee14c7837c50ee2ba223fbe1c5b' },
  { fileName: 'cloudogu.d.ts', sha256: '5f35aa2b09e79c70f335bf11ffffb95183fc309333b9bf9c822f50849a40bf28' },
  { fileName: 'cloudogu.js', sha256: '23ab67b8cc4a5795d32a37da1a3aa0c689a78fbe6580ce42460cbcaa0c1c860f' },
  { fileName: 'index.d.ts', sha256: 'fec566ad9aa65360b47900983a6643e79430e0ee25b1ea4c0908d82d09761b48' },
  { fileName: 'index.js', sha256: 'fec566ad9aa65360b47900983a6643e79430e0ee25b1ea4c0908d82d09761b48' },
];

describe('acceptance 2: packages/stdlib is byte-identical to before this change', () => {
  it.each(STDLIB_PINNED_DIGESTS)('$fileName matches its pinned sha256', ({ fileName, sha256 }) => {
    const bytes = readGeneratedBytes('stdlib', fileName);
    expect(sha256Hex(bytes)).toBe(sha256);
  },
    120_000);
});

// ---------------------------------------------------------------------------
// Acceptance 3: the eager modules for stdlib-aws / stdlib-tupadr3 do not
// exist anywhere in the built tree.
// ---------------------------------------------------------------------------

describe('acceptance 3: the removed eager modules do not exist', () => {
  it('packages/stdlib-aws/generated/awslib14.js does not exist', () => {
    expect(generatedExists('stdlib-aws', 'awslib14.js')).toBe(false);
  },
    120_000);

  it('packages/stdlib-aws/generated/awslib.js does not exist', () => {
    expect(generatedExists('stdlib-aws', 'awslib.js')).toBe(false);
  },
    120_000);

  it('packages/stdlib-tupadr3/generated/tupadr3.js does not exist', () => {
    expect(generatedExists('stdlib-tupadr3', 'tupadr3.js')).toBe(false);
  },
    120_000);
});
