/**
 * SI12 T2 -- pins `packages/stdlib-all`'s export surface.
 *
 * ADR-4: after SI12, `stdlib-aws` and `stdlib-tupadr3` no longer ship eager
 * bundles, only remote manifests. `emit-all-index.ts` re-exports `stdlib`'s
 * five eager bundles (six bindings -- `bootstrap` carries both the alias and
 * its `bootstrap1_13_1` target) PLUS the three remote manifests
 * (`awslib14Remote`, `awslibRemote`, `tupadr3Remote`) by NAME rather than
 * `export *`, so a future edit that drops one binding is silent unless a
 * test asserts each name individually. This file is that test -- on-call
 * failure mode #3's detection mechanism (`decisions.md` ADR-4).
 *
 * Reads the BUILT `packages/stdlib-all/generated/index.js` off disk (built
 * once by `tests/helpers/build-stdlib-globalsetup.ts`) rather than rebuilding
 * it -- rebuilding from inside a test races other parallel workers importing
 * out of the same tree (see that file's docstring).
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { describe, expect, it } from 'vitest';

import { emitAllIndexDts, emitAllIndexJs } from '../../scripts/build-stdlib-packages/emit-all-index.js';
import { withStdlibBuildLock } from '../helpers/with-stdlib-build-lock.js';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const STDLIB_ALL_GENERATED_DIR = join(REPO_ROOT, 'packages', 'stdlib-all', 'generated');

interface BundleDataLike {
  readonly name: string;
  readonly aliasOf?: string;
  readonly files: Record<string, string>;
}

interface RemoteManifestLike {
  readonly name: string;
  readonly aliasOf?: string;
  readonly files: Record<string, string>;
}

type StdlibAllExports = {
  readonly c4: BundleDataLike;
  readonly archimate: BundleDataLike;
  readonly cloudinsight: BundleDataLike;
  readonly cloudogu: BundleDataLike;
  readonly bootstrap: BundleDataLike;
  readonly bootstrap1_13_1: BundleDataLike;
  readonly awslib14Remote: RemoteManifestLike;
  readonly awslibRemote: RemoteManifestLike;
  readonly tupadr3Remote: RemoteManifestLike;
};

/** stdlib-run-isolation T4: held for exactly this one dynamic `import()` --
 * the narrowest span that touches `packages/stdlib-all/generated/`. */
async function importBuiltIndex(): Promise<StdlibAllExports> {
  return withStdlibBuildLock(() => {
    const path = join(STDLIB_ALL_GENERATED_DIR, 'index.js');
    return import(pathToFileURL(path).href) as Promise<StdlibAllExports>;
  });
}

// ---------------------------------------------------------------------------
// Acceptance 1: the pure emitter's source text names every export
// individually -- pins the generator so removing any ONE named export from
// `emit-all-index.ts` fails this exact-string comparison.
// ---------------------------------------------------------------------------

const EXPECTED_JS =
  '// AUTO-GENERATED by scripts/build-stdlib-packages.ts -- DO NOT EDIT.\n' +
  '// Regenerate with: npm run build:stdlib\n' +
  '\n' +
  'export { c4, archimate, cloudinsight, cloudogu, bootstrap, bootstrap1_13_1 } ' +
  "from '@knowvah/plantuml-stdlib';\n" +
  "export { awslib14Remote, awslibRemote } from '@knowvah/plantuml-stdlib-aws';\n" +
  "export { tupadr3Remote } from '@knowvah/plantuml-stdlib-tupadr3';\n";

describe('acceptance 1: emit-all-index.ts source pins every export by name', () => {
  it('emitAllIndexJs() produces the exact expected source', () => {
    expect(emitAllIndexJs()).toBe(EXPECTED_JS);
  });

  it('emitAllIndexDts() produces the exact expected source', () => {
    expect(emitAllIndexDts()).toBe(EXPECTED_JS);
  });
});

// ---------------------------------------------------------------------------
// Acceptance 2: the BUILT generated/index.js on disk matches the emitter
// output byte-for-byte -- proves the generator is actually wired to
// `buildAllPackage()`, not just correct in isolation.
// ---------------------------------------------------------------------------

describe('acceptance 2: the built index.js on disk matches the emitter', () => {
  it('generated/index.js is byte-identical to a fresh emit', () => {
    const onDisk = withStdlibBuildLock(() => readFileSync(join(STDLIB_ALL_GENERATED_DIR, 'index.js'), 'utf8'));
    expect(onDisk).toBe(emitAllIndexJs());
  },
    120_000);

  it('generated/index.d.ts is byte-identical to a fresh emit', () => {
    const onDisk = withStdlibBuildLock(() => readFileSync(join(STDLIB_ALL_GENERATED_DIR, 'index.d.ts'), 'utf8'));
    expect(onDisk).toBe(emitAllIndexDts());
  },
    120_000);
});

// ---------------------------------------------------------------------------
// Acceptance 3: each of the nine export bindings actually resolves at
// runtime, with the expected shape -- asserted individually by name, not by
// `Object.keys(...).length`, so dropping any single one fails its own case.
// ---------------------------------------------------------------------------

describe("acceptance 3: stdlib-all's built index exports each binding by name", () => {
  it('re-exports stdlib.c4 (eager, concrete)', async () => {
    const mod = await importBuiltIndex();
    expect(mod.c4.name).toBe('C4');
    expect(Object.keys(mod.c4.files).length).toBeGreaterThan(0);
  },
    120_000);

  it('re-exports stdlib.archimate (eager, concrete)', async () => {
    const mod = await importBuiltIndex();
    expect(mod.archimate.name).toBe('archimate');
    expect(Object.keys(mod.archimate.files).length).toBeGreaterThan(0);
  },
    120_000);

  it('re-exports stdlib.cloudinsight (eager, concrete)', async () => {
    const mod = await importBuiltIndex();
    expect(mod.cloudinsight.name).toBe('cloudinsight');
    expect(Object.keys(mod.cloudinsight.files).length).toBeGreaterThan(0);
  },
    120_000);

  it('re-exports stdlib.cloudogu (eager, concrete)', async () => {
    const mod = await importBuiltIndex();
    expect(mod.cloudogu.name).toBe('cloudogu');
    expect(Object.keys(mod.cloudogu.files).length).toBeGreaterThan(0);
  },
    120_000);

  it('re-exports stdlib.bootstrap (eager, alias of bootstrap1.13.1)', async () => {
    const mod = await importBuiltIndex();
    expect(mod.bootstrap.name).toBe('bootstrap');
    expect(mod.bootstrap.aliasOf).toBe('bootstrap1.13.1');
    expect(Object.keys(mod.bootstrap.files)).toHaveLength(0);
  },
    120_000);

  it('re-exports stdlib.bootstrap1_13_1 (eager, concrete target)', async () => {
    const mod = await importBuiltIndex();
    expect(mod.bootstrap1_13_1.name).toBe('bootstrap1.13.1');
    expect(Object.keys(mod.bootstrap1_13_1.files).length).toBeGreaterThan(0);
  },
    120_000);

  it('re-exports stdlib-aws.awslib14Remote (manifest, concrete)', async () => {
    const mod = await importBuiltIndex();
    expect(mod.awslib14Remote.name).toBe('awslib14');
    expect(Object.keys(mod.awslib14Remote.files).length).toBeGreaterThan(0);
  },
    120_000);

  it('re-exports stdlib-aws.awslibRemote (manifest, alias of awslib14)', async () => {
    const mod = await importBuiltIndex();
    expect(mod.awslibRemote.name).toBe('awslib');
    expect(mod.awslibRemote.aliasOf).toBe('awslib14');
    expect(Object.keys(mod.awslibRemote.files)).toHaveLength(0);
  },
    120_000);

  it('re-exports stdlib-tupadr3.tupadr3Remote (manifest, concrete)', async () => {
    const mod = await importBuiltIndex();
    expect(mod.tupadr3Remote.name).toBe('tupadr3');
    expect(Object.keys(mod.tupadr3Remote.files).length).toBeGreaterThan(0);
  },
    120_000);
});
