/**
 * SI12 T1 -- the generator stops EMITTING eager modules for `stdlib-aws` and
 * `stdlib-tupadr3` (`plans/si12-eager-module-removal/batch-1/T1-generator-omits-eager.md`,
 * ADR-1/ADR-2/ADR-5).
 *
 * `packages/*\/generated/` is built ONCE by vitest's globalSetup
 * (`tests/helpers/build-stdlib-globalsetup.ts`), not here -- rebuilding it in
 * a per-file `beforeAll` races the other test files reading the same tree
 * (`tests/unit/stdlib-packages.test.ts` documents the failure mode). Every
 * assertion below reads bytes already on disk.
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const PACKAGES_DIR = join(REPO_ROOT, 'packages');

function sha256Hex(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

function generatedPath(packageDir: string, fileName: string): string {
  return join(PACKAGES_DIR, packageDir, 'generated', fileName);
}

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/build-stdlib-packages.ts -- DO NOT EDIT.\n' +
  '// Regenerate with: npm run build:stdlib\n';

// ---------------------------------------------------------------------------
// Acceptance 1: no eager module file, `generated/index.js` re-exports the
// remote manifest bindings instead (ADR-1).
// ---------------------------------------------------------------------------

describe('acceptance 1: stdlib-aws ships no eager module', () => {
  const EXPECTED_INDEX =
    GENERATED_HEADER +
    '\n' +
    "export { awslib14Remote } from './awslib14.remote.js';\n" +
    "export { awslibRemote } from './awslib.remote.js';\n";

  it('generated/index.js re-exports awslib14Remote and awslibRemote', () => {
    const indexJs = readFileSync(generatedPath('stdlib-aws', 'index.js'), 'utf8');
    expect(indexJs).toBe(EXPECTED_INDEX);
  });

  it('generated/index.d.ts re-exports the same bindings', () => {
    const indexDts = readFileSync(generatedPath('stdlib-aws', 'index.d.ts'), 'utf8');
    expect(indexDts).toBe(EXPECTED_INDEX);
  });

  it('awslib14.js and awslib.js are not emitted', () => {
    expect(existsSync(generatedPath('stdlib-aws', 'awslib14.js'))).toBe(false);
    expect(existsSync(generatedPath('stdlib-aws', 'awslib.js'))).toBe(false);
    expect(existsSync(generatedPath('stdlib-aws', 'awslib14.d.ts'))).toBe(false);
    expect(existsSync(generatedPath('stdlib-aws', 'awslib.d.ts'))).toBe(false);
  });

  it('the remote manifest siblings are emitted instead', () => {
    expect(existsSync(generatedPath('stdlib-aws', 'awslib14.remote.js'))).toBe(true);
    expect(existsSync(generatedPath('stdlib-aws', 'awslib.remote.js'))).toBe(true);
  });
});

describe('acceptance 1: stdlib-tupadr3 ships no eager module', () => {
  const EXPECTED_INDEX = GENERATED_HEADER + '\n' + "export { tupadr3Remote } from './tupadr3.remote.js';\n";

  it('generated/index.js re-exports tupadr3Remote', () => {
    const indexJs = readFileSync(generatedPath('stdlib-tupadr3', 'index.js'), 'utf8');
    expect(indexJs).toBe(EXPECTED_INDEX);
  });

  it('generated/index.d.ts re-exports the same binding', () => {
    const indexDts = readFileSync(generatedPath('stdlib-tupadr3', 'index.d.ts'), 'utf8');
    expect(indexDts).toBe(EXPECTED_INDEX);
  });

  it('tupadr3.js is not emitted', () => {
    expect(existsSync(generatedPath('stdlib-tupadr3', 'tupadr3.js'))).toBe(false);
    expect(existsSync(generatedPath('stdlib-tupadr3', 'tupadr3.d.ts'))).toBe(false);
  });

  it('the remote manifest sibling is emitted instead', () => {
    expect(existsSync(generatedPath('stdlib-tupadr3', 'tupadr3.remote.js'))).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Acceptance 2: packages/stdlib's five eager modules stay byte-identical.
// Digests pinned from the pre-SI12 tree
// (`plans/si12-eager-module-removal/batch-1/T1-generator-omits-eager.md`).
// ---------------------------------------------------------------------------

interface PinnedFile {
  readonly fileName: string;
  readonly sha256: string;
}

const STDLIB_PINNED_DIGESTS: readonly PinnedFile[] = [
  { fileName: 'archimate.d.ts', sha256: '308cbf7452b62e32b5cd8bc449130a4e435966501ebb7147cba9d6863c43559d' },
  { fileName: 'archimate.js', sha256: '2b7cc62394934490272f23307517ed21b05c4534f92758369bf2d7ec0e08878f' },
  { fileName: 'bootstrap.d.ts', sha256: '5f9cbcb30415997c266de6fe96f179209bc6d7e0f2576068aa0b5dee63302fd3' },
  { fileName: 'bootstrap.js', sha256: '29fefcebde1e4896d5687c8ad1fc57213e9d2690213048d899846d0de392ea5f' },
  { fileName: 'c4.d.ts', sha256: '26aff90c549014026742cee858af83a6ae98cf634d68a41322dbc5d9a1ad309f' },
  { fileName: 'c4.js', sha256: 'f7929a5a2efdfd453e7889677ffc89f3fd050a4915139f2149838c8fd65cb0c7' },
  { fileName: 'cloudinsight.d.ts', sha256: '1ac36b58161f8a4026583e4b3f7a6eb8b19147b4879454afd863aa0ac2694e78' },
  { fileName: 'cloudinsight.js', sha256: '26edf20eef9bc3b79bd8affdc1d2f16f2ffa3ee14c7837c50ee2ba223fbe1c5b' },
  { fileName: 'cloudogu.d.ts', sha256: 'b58c1349ddc8533f6f2397ba9bc7ca6c4f1e0ebece46cf60aba1f7c84b9c475c' },
  { fileName: 'cloudogu.js', sha256: '23ab67b8cc4a5795d32a37da1a3aa0c689a78fbe6580ce42460cbcaa0c1c860f' },
  { fileName: 'index.d.ts', sha256: 'fec566ad9aa65360b47900983a6643e79430e0ee25b1ea4c0908d82d09761b48' },
  { fileName: 'index.js', sha256: 'fec566ad9aa65360b47900983a6643e79430e0ee25b1ea4c0908d82d09761b48' },
];

describe('acceptance 2: packages/stdlib is byte-identical to before this change', () => {
  it.each(STDLIB_PINNED_DIGESTS)('$fileName matches its pinned sha256', ({ fileName, sha256 }) => {
    const bytes = readFileSync(generatedPath('stdlib', fileName));
    expect(sha256Hex(bytes)).toBe(sha256);
  });
});

// ---------------------------------------------------------------------------
// Acceptance 3: the eager modules for stdlib-aws / stdlib-tupadr3 do not
// exist anywhere in the built tree.
// ---------------------------------------------------------------------------

describe('acceptance 3: the removed eager modules do not exist', () => {
  it('packages/stdlib-aws/generated/awslib14.js does not exist', () => {
    expect(existsSync(generatedPath('stdlib-aws', 'awslib14.js'))).toBe(false);
  });

  it('packages/stdlib-aws/generated/awslib.js does not exist', () => {
    expect(existsSync(generatedPath('stdlib-aws', 'awslib.js'))).toBe(false);
  });

  it('packages/stdlib-tupadr3/generated/tupadr3.js does not exist', () => {
    expect(existsSync(generatedPath('stdlib-tupadr3', 'tupadr3.js'))).toBe(false);
  });
});
